// GENERATED CODE - DO NOT MODIFY BY HAND.
// Built only from 100% approved recommendation translations.

import 'recommendation_catalog_models.dart';

const recommendationCatalogVersion = '2026-07-29.1';
const recommendationSourceRegistryVersion = '2026-07-29.1';
const recommendationCatalogChecksum =
    'ed67933430ff3a341b2e0597bdaf3ce1049fd9b7e3f7b8a7fe408b159d256e47';

const generatedRecommendationCatalog = <RecommendationCatalogItem>[
  RecommendationCatalogItem(
    id: 'act_adj_eye_level.01',
    selectionKey: 'act_adj_eye_level',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ปรับงานให้อยู่ระดับสายตา',
    englishText: 'Adjust the work to eye level.',
    sourceId: 'body_map_recommendations',
    sourcePage: '1-2',
  ),
  RecommendationCatalogItem(
    id: 'act_adj_eye_level.02',
    selectionKey: 'act_adj_eye_level',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดการก้มคอ',
    englishText: 'Reduce neck bending.',
    sourceId: 'body_map_recommendations',
    sourcePage: '1-2',
  ),
  RecommendationCatalogItem(
    id: 'act_adj_wrist.01',
    selectionKey: 'act_adj_wrist',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ปรับด้ามจับเครื่องมือให้ข้อมืออยู่ในแนวตรง',
    englishText: 'Keep the wrist in a neutral position.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5-6',
  ),
  RecommendationCatalogItem(
    id: 'act_avoid_bend.01',
    selectionKey: 'act_avoid_bend',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดการก้มโดยยกพื้นที่ทำงานให้สูงขึ้น',
    englishText: 'Reduce bending by raising the work area.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2-3',
  ),
  RecommendationCatalogItem(
    id: 'act_avoid_twist.01',
    selectionKey: 'act_avoid_twist',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'หลีกเลี่ยงการบิดลำตัวหรือเอียงตัวขณะทำงาน',
    englishText: 'Avoid twisting or side bending while working.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2-3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_high.01',
    selectionKey: 'act_body_arms_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'high',
    thaiText: 'ไม่ยกแขนเหนือไหล่ต่อเนื่องเกิน 2 นาที',
    englishText:
        'Do not keep arms above shoulder level for more than 2 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_high.02',
    selectionKey: 'act_body_arms_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'high',
    thaiText: 'พักแขน 3-5 นาทีทุก 15-20 นาที',
    englishText: 'Rest 3-5 minutes every 15-20 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_high.03',
    selectionKey: 'act_body_arms_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'high',
    thaiText: 'ใช้เครื่องมือด้ามยาวหรือแท่นยืนที่มั่นคง',
    englishText: 'Use long-handled tools or a stable platform.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_medium.01',
    selectionKey: 'act_body_arms_medium',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'medium',
    thaiText: 'จัดวัสดุให้อยู่ในระยะเอื้อมไม่เกิน 40 ซม.',
    englishText: 'Keep materials within 40 cm of the body.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_medium.02',
    selectionKey: 'act_body_arms_medium',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'medium',
    thaiText: 'วางอุปกรณ์เมื่อไม่ใช้',
    englishText: 'Put tools down when they are not in use.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_medium.03',
    selectionKey: 'act_body_arms_medium',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'medium',
    thaiText: 'พักไหล่ทุก 30 นาที และให้งานอยู่ต่ำกว่าระดับไหล่',
    englishText:
        'Rest the shoulders every 30 minutes and keep the work below shoulder height.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_very_high.01',
    selectionKey: 'act_body_arms_very_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'very_high',
    thaiText: 'จำกัดงานเหนือศีรษะเป็นรอบสั้น',
    englishText: 'Limit overhead work to short rounds.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4-5',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_very_high.02',
    selectionKey: 'act_body_arms_very_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'very_high',
    thaiText: 'ใช้เครื่องมือด้ามยาวที่น้ำหนักเบา',
    englishText: 'Use lighter long-handled tools.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4-5',
  ),
  RecommendationCatalogItem(
    id: 'act_body_arms_very_high.03',
    selectionKey: 'act_body_arms_very_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'arms',
    riskLevel: 'very_high',
    thaiText: 'สลับไปทำงานที่ใช้แขนต่ำกว่าระดับไหล่',
    englishText: 'Rotate to work below shoulder level.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4-5',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_high.01',
    selectionKey: 'act_body_legs_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'high',
    thaiText: 'ไม่นั่งยองหรือคุกเข่าต่อเนื่องเกิน 15 นาที',
    englishText: 'Do not squat or kneel continuously for more than 15 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6-7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_high.02',
    selectionKey: 'act_body_legs_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'high',
    thaiText: 'ลุกเดิน 3-5 นาทีทุก 15 นาที',
    englishText: 'Walk 3-5 minutes every 15 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6-7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_high.03',
    selectionKey: 'act_body_legs_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'high',
    thaiText: 'ใช้เก้าอี้เตี้ยหรือแผ่นรองเข่า',
    englishText: 'Use a low stool or knee pad.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6-7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_medium.01',
    selectionKey: 'act_body_legs_medium',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'medium',
    thaiText: 'ลุกยืนหรือเดินทุก 20 นาที',
    englishText: 'Stand up or walk every 20 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_medium.02',
    selectionKey: 'act_body_legs_medium',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'medium',
    thaiText: 'ใช้เบาะรองนั่งหรือแผ่นรองเข่า',
    englishText: 'Use a squatting cushion or knee pad.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_medium.03',
    selectionKey: 'act_body_legs_medium',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'medium',
    thaiText: 'สลับระหว่างนั่ง ยืน และเดิน',
    englishText: 'Alternate between sitting, standing, and walking.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_very_high.01',
    selectionKey: 'act_body_legs_very_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'very_high',
    thaiText: 'หลีกเลี่ยงการนั่งยองหรือคุกเข่าเกิน 10 นาที',
    englishText: 'Avoid squatting or kneeling for more than 10 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_very_high.02',
    selectionKey: 'act_body_legs_very_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'very_high',
    thaiText: 'พักทุก 10-15 นาที',
    englishText: 'Rest every 10-15 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_very_high.03',
    selectionKey: 'act_body_legs_very_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'very_high',
    thaiText: 'ใช้อุปกรณ์ช่วยทำงานระดับพื้น',
    englishText: 'Use floor-work aids.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_legs_very_high.04',
    selectionKey: 'act_body_legs_very_high',
    displayOrder: 4,
    category: 'posture',
    activity: 'any',
    bodyPart: 'legs',
    riskLevel: 'very_high',
    thaiText: 'ลดเวลาทำงานใกล้พื้น',
    englishText: 'Reduce time working near the ground.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_high.01',
    selectionKey: 'act_body_manual_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'แบ่งน้ำหนักต่อครั้งไม่เกิน 10 กก.',
    englishText: 'Limit each load to no more than 10 kg.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7-8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_high.02',
    selectionKey: 'act_body_manual_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText:
        'ใช้รถเข็นเมื่อขนไกลกว่า 10 เมตร ให้ 2 คนช่วยยกเมื่อหนักเกิน 20 กก.',
    englishText:
        'Use a cart for distances over 10 m, and use 2-person lifting for loads over 20 kg.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7-8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_high.03',
    selectionKey: 'act_body_manual_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'หลีกเลี่ยงการบิดตัวขณะยก',
    englishText: 'Avoid twisting while lifting.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7-8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_medium.01',
    selectionKey: 'act_body_manual_medium',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'แบ่งถุงหรือภาชนะให้หนักไม่เกิน 15 กก.',
    englishText:
        'Divide materials into bags or containers weighing no more than 15 kg each.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_medium.02',
    selectionKey: 'act_body_manual_medium',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'ถือของให้ชิดลำตัว',
    englishText: 'Keep the load close to the body.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_medium.03',
    selectionKey: 'act_body_manual_medium',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'ใช้สองมือช่วยยก',
    englishText: 'Lift with both hands.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_medium.04',
    selectionKey: 'act_body_manual_medium',
    displayOrder: 4,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'หลีกเลี่ยงการยกเหนือระดับไหล่',
    englishText: 'Avoid lifting above shoulder height.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_very_high.01',
    selectionKey: 'act_body_manual_very_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'very_high',
    thaiText: 'ใช้รถเข็น รถลาก หรืออุปกรณ์ช่วยยก',
    englishText: 'Use a cart, trolley, or lifting aid.',
    sourceId: 'body_map_recommendations',
    sourcePage: '8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_very_high.02',
    selectionKey: 'act_body_manual_very_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'very_high',
    thaiText: 'หลีกเลี่ยงการยกเกิน 20 กก. คนเดียว',
    englishText: 'Avoid lifting more than 20 kg alone.',
    sourceId: 'body_map_recommendations',
    sourcePage: '8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_very_high.03',
    selectionKey: 'act_body_manual_very_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'very_high',
    thaiText: 'ถ้าหนัก 20-25 กก. ให้ช่วยกันยก',
    englishText: 'Use at least two people to lift loads of 20-25 kg.',
    sourceId: 'body_map_recommendations',
    sourcePage: '8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_manual_very_high.04',
    selectionKey: 'act_body_manual_very_high',
    displayOrder: 4,
    category: 'posture',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'very_high',
    thaiText: 'ถ้าเกิน 25 กก. ให้ใช้อุปกรณ์ช่วย',
    englishText: 'Use lifting equipment for loads over 25 kg.',
    sourceId: 'body_map_recommendations',
    sourcePage: '8',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_high.01',
    selectionKey: 'act_body_neck_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'high',
    thaiText: 'ปรับพื้นที่ทำงานให้สูงขึ้น ยืดเหยียดคอทุก 15-20 นาที',
    englishText:
        'Raise the work area and stretch the neck every 15-20 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_high.02',
    selectionKey: 'act_body_neck_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'high',
    thaiText: 'ใช้อุปกรณ์ช่วยหยิบจับ',
    englishText: 'Use a reaching aid.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_high.03',
    selectionKey: 'act_body_neck_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'high',
    thaiText: 'หลีกเลี่ยงการบิดหรือเอียงคอ',
    englishText: 'Avoid twisting or tilting the neck.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_medium.01',
    selectionKey: 'act_body_neck_medium',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'medium',
    thaiText: 'ยกถาดหรือวัสดุให้อยู่ระดับเอว',
    englishText: 'Raise trays or materials to waist height.',
    sourceId: 'body_map_recommendations',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_medium.02',
    selectionKey: 'act_body_neck_medium',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'medium',
    thaiText: 'เปลี่ยนท่าคอทุก 30 นาที',
    englishText: 'Change neck posture every 30 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_medium.03',
    selectionKey: 'act_body_neck_medium',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'medium',
    thaiText: 'หลีกเลี่ยงการก้มมองพื้นต่อเนื่อง',
    englishText: 'Avoid looking down continuously.',
    sourceId: 'body_map_recommendations',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_very_high.01',
    selectionKey: 'act_body_neck_very_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'very_high',
    thaiText: 'ปรับวิธีทำงานทันที',
    englishText: 'Change the work method immediately.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_very_high.02',
    selectionKey: 'act_body_neck_very_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'very_high',
    thaiText: 'ยกวัสดุขึ้นระดับเอว',
    englishText: 'Raise materials to waist height.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_very_high.03',
    selectionKey: 'act_body_neck_very_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'very_high',
    thaiText: 'ใช้เครื่องมือด้ามยาว',
    englishText: 'Use long-handled tools.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_neck_very_high.04',
    selectionKey: 'act_body_neck_very_high',
    displayOrder: 4,
    category: 'posture',
    activity: 'any',
    bodyPart: 'neck',
    riskLevel: 'very_high',
    thaiText: 'เปลี่ยนอิริยาบถทุก 10-15 นาที',
    englishText: 'Change posture every 10-15 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_high.01',
    selectionKey: 'act_body_trunk_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'high',
    thaiText: 'หลีกเลี่ยงการก้มต่อเนื่องเกิน 10-15 นาที ยืดเหยียดทุก 15 นาที',
    englishText:
        'Avoid continuous bending for more than 10-15 minutes and stretch every 15 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_high.02',
    selectionKey: 'act_body_trunk_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'high',
    thaiText: 'หันหน้าเข้าหาวัสดุก่อนยก',
    englishText: 'Face the material before lifting.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_high.03',
    selectionKey: 'act_body_trunk_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'high',
    thaiText: 'หมุนเท้าแทนการบิดเอว',
    englishText: 'Turn with the feet instead of twisting the waist.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_medium.01',
    selectionKey: 'act_body_trunk_medium',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'medium',
    thaiText: 'วางวัสดุให้อยู่ใกล้ตัวไม่เกิน 40 ซม.',
    englishText: 'Keep materials within 40 cm.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_medium.02',
    selectionKey: 'act_body_trunk_medium',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'medium',
    thaiText: 'ยกงานจากพื้น 50-70 ซม.',
    englishText: 'Raise work from the ground by 50-70 cm.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_medium.03',
    selectionKey: 'act_body_trunk_medium',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'medium',
    thaiText: 'ลุกเปลี่ยนท่าทุก 20-30 นาที',
    englishText: 'Stand up to change posture every 20-30 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_very_high.01',
    selectionKey: 'act_body_trunk_very_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'very_high',
    thaiText: 'ใช้รถเข็นหรืออุปกรณ์ช่วยยก',
    englishText: 'Use carts or lifting aids.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3-4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_very_high.02',
    selectionKey: 'act_body_trunk_very_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'very_high',
    thaiText: 'หลีกเลี่ยงการยกเกิน 20 กก. คนเดียว',
    englishText: 'Avoid lifting more than 20 kg alone.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3-4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_very_high.03',
    selectionKey: 'act_body_trunk_very_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'very_high',
    thaiText: 'ปรับงานให้อยู่ระดับเข่าถึงเอว',
    englishText: 'Raise the work area to knee-to-waist height.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3-4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_trunk_very_high.04',
    selectionKey: 'act_body_trunk_very_high',
    displayOrder: 4,
    category: 'posture',
    activity: 'any',
    bodyPart: 'trunk',
    riskLevel: 'very_high',
    thaiText: 'ลดการขนย้ายที่ไม่จำเป็น',
    englishText: 'Reduce unnecessary carries.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3-4',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_high.01',
    selectionKey: 'act_body_wrists_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'high',
    thaiText: 'พักมือและข้อมือทุก 15-20 นาที',
    englishText: 'Rest the hands and wrists every 15-20 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5-6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_high.02',
    selectionKey: 'act_body_wrists_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'high',
    thaiText: 'สลับงานทุก 20-30 นาที',
    englishText: 'Rotate tasks every 20-30 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5-6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_high.03',
    selectionKey: 'act_body_wrists_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'high',
    thaiText: 'ใช้ด้ามจับที่เหมาะสม',
    englishText: 'Use suitable handles.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5-6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_high.04',
    selectionKey: 'act_body_wrists_high',
    displayOrder: 4,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'high',
    thaiText: 'ลดแรงกำขณะจับอุปกรณ์',
    englishText: 'Reduce gripping force when holding equipment.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5-6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_medium.01',
    selectionKey: 'act_body_wrists_medium',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'medium',
    thaiText: 'ใช้ด้ามจับที่พอดีมือ',
    englishText: 'Use handles that fit the hand.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_medium.02',
    selectionKey: 'act_body_wrists_medium',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'medium',
    thaiText: 'คลายมือเป็นระยะ',
    englishText: 'Relax the grip regularly.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_medium.03',
    selectionKey: 'act_body_wrists_medium',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'medium',
    thaiText: 'พักข้อมือทุก 30 นาที และยืดเหยียดนิ้วมือกับข้อมือระหว่างพัก',
    englishText:
        'Rest the wrists every 30 minutes and stretch the fingers and wrists during breaks.',
    sourceId: 'body_map_recommendations',
    sourcePage: '5',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_very_high.01',
    selectionKey: 'act_body_wrists_very_high',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'very_high',
    thaiText: 'พักข้อมือ 3-5 นาทีทุก 15 นาที',
    englishText: 'Rest wrists 3-5 minutes every 15 minutes.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_very_high.02',
    selectionKey: 'act_body_wrists_very_high',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'very_high',
    thaiText: 'เปลี่ยนเครื่องมือให้พอดีกับมือ',
    englishText: 'Change to better-fitting tools.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6',
  ),
  RecommendationCatalogItem(
    id: 'act_body_wrists_very_high.03',
    selectionKey: 'act_body_wrists_very_high',
    displayOrder: 3,
    category: 'posture',
    activity: 'any',
    bodyPart: 'wrists',
    riskLevel: 'very_high',
    thaiText: 'ใช้อุปกรณ์ช่วยลดแรงกำหรือแรงบีบที่ไม่จำเป็น',
    englishText:
        'Use aids that reduce unnecessary gripping or squeezing force.',
    sourceId: 'body_map_recommendations',
    sourcePage: '6',
  ),
  RecommendationCatalogItem(
    id: 'act_check_wheels.01',
    selectionKey: 'act_check_wheels',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ตรวจสอบล้อรถเข็นว่าฝืดหรือไม่',
    englishText: 'Check cart wheels for friction.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '37',
  ),
  RecommendationCatalogItem(
    id: 'act_extra_fert_cart.01',
    selectionKey: 'act_extra_fert_cart',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้รถเข็นบรรทุกกระสอบปุ๋ยแทนการแบก',
    englishText:
        'Use a cart to carry fertilizer sacks instead of carrying them on the body.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_extra_prune_ladder.01',
    selectionKey: 'act_extra_prune_ladder',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้บันไดที่มั่นคงแทนการเอื้อมสุดแขน',
    englishText:
        'Use a stable ladder instead of reaching with the arm fully extended.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_extra_prune_tool.01',
    selectionKey: 'act_extra_prune_tool',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้กรรไกรตัดกิ่งด้ามยาว',
    englishText: 'Use long-handled pruning shears.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_extra_spray_strap.01',
    selectionKey: 'act_extra_spray_strap',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ปรับสายสะพายเครื่องพ่นยาให้กระชับ',
    englishText: 'Adjust the sprayer straps so they fit securely.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_extra_spray_switch.01',
    selectionKey: 'act_extra_spray_switch',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'สลับข้างสะพายถังเพื่อลดการกดทับไหล่เดียว',
    englishText:
        'Alternate the shoulder used to carry the tank to reduce pressure on one shoulder.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_high.01',
    selectionKey: 'act_fert_ref_high',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ลดน้ำหนักปุ๋ยต่อครั้ง',
    englishText: 'Reduce fertilizer weight per trip.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_high.02',
    selectionKey: 'act_fert_ref_high',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ใช้สายพานหรือรถเข็น',
    englishText: 'Use a conveyor or cart.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_high.03',
    selectionKey: 'act_fert_ref_high',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'จัดพัก 10 นาทีทุกชั่วโมง',
    englishText: 'Rest 10 minutes every hour.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_high.04',
    selectionKey: 'act_fert_ref_high',
    displayOrder: 4,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'หลีกเลี่ยงการทำงานบนพื้นที่ลาดชันต่อเนื่อง',
    englishText: 'Avoid continuous work on slopes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_low.01',
    selectionKey: 'act_fert_ref_low',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText:
        'ใช้รถเข็นถ้าต้องเคลื่อนย้ายปุ๋ยไกล และหมั่นเปลี่ยนท่าทางทุก 30 นาที',
    englishText:
        'Use a cart when fertilizer must be moved over a long distance, and change posture every 30 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_medium.01',
    selectionKey: 'act_fert_ref_medium',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'แบ่งปุ๋ยใส่ภาชนะเล็ก',
    englishText: 'Split fertilizer into smaller containers.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_medium.02',
    selectionKey: 'act_fert_ref_medium',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ใช้รถเข็น',
    englishText: 'Use a cart.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_ref_medium.03',
    selectionKey: 'act_fert_ref_medium',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'fertilizing',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'หลีกเลี่ยงการบิดตัวขณะยก และใส่รองเท้ากันลื่น',
    englishText: 'Avoid twisting while lifting and wear non-slip footwear.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_fert_split_load.01',
    selectionKey: 'act_fert_split_load',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'แบ่งปุ๋ยเป็นน้ำหนักน้อยลงในแต่ละรอบ',
    englishText: 'Split fertilizer into smaller loads per round.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_empty_often.01',
    selectionKey: 'act_harvest_empty_often',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดการก้มโดยปรับความสูงตะกร้า',
    englishText: 'Raise the basket to reduce bending.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_move_closer.01',
    selectionKey: 'act_harvest_move_closer',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ขยับเข้าใกล้ต้นก่อนเก็บ เพื่อลดการเอื้อมไกล',
    englishText:
        'Move closer to the plant before picking instead of overreaching.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_high.01',
    selectionKey: 'act_harvest_ref_high',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ถ้าเก็บผลจากกิ่งสูงต้องใช้บันได',
    englishText: 'Use a ladder for high branches.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_high.02',
    selectionKey: 'act_harvest_ref_high',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'หลีกเลี่ยงการปีน',
    englishText: 'Avoid climbing.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_high.03',
    selectionKey: 'act_harvest_ref_high',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'หยุดพัก 10 นาทีทุก 20 นาที',
    englishText: 'Rest 10 minutes every 20 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_high.04',
    selectionKey: 'act_harvest_ref_high',
    displayOrder: 4,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ถ้ามีอาการปวดมือหรือหลังให้หยุดงานทันที',
    englishText: 'Stop immediately if hand or back pain occurs.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_low.01',
    selectionKey: 'act_harvest_ref_low',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'เปลี่ยนท่า ยืน-นั่งยอง ทุก 20 นาที',
    englishText: 'Alternate between standing and squatting every 20 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_low.02',
    selectionKey: 'act_harvest_ref_low',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ใช้ถุงมือนุ่ม และตั้งตะกร้าบนแท่นสูง',
    englishText: 'Use soft gloves and place the basket on a raised stand.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_medium.01',
    selectionKey: 'act_harvest_ref_medium',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ใช้ถุงมือลดแรงกด',
    englishText: 'Use padded gloves.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_medium.02',
    selectionKey: 'act_harvest_ref_medium',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ลดการก้มโดยปรับความสูงตะกร้า',
    englishText: 'Reduce bending by raising the basket.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_medium.03',
    selectionKey: 'act_harvest_ref_medium',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'พัก 5 นาทีทุก 30 นาที',
    englishText: 'Rest 5 minutes every 30 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_harvest_ref_medium.04',
    selectionKey: 'act_harvest_ref_medium',
    displayOrder: 4,
    category: 'riskReduction',
    activity: 'harvesting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'สังเกตอาการชาที่มือ',
    englishText: 'Watch for hand numbness.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_floor_level.01',
    selectionKey: 'act_iso_floor_level',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'จัดพื้นทางเดินให้เรียบ แห้ง ไม่ลื่น และไม่มีสิ่งกีดขวาง',
    englishText:
        'Keep the transport surface level, dry, non-slip, and clear of obstacles.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '29,31',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_improve_grip.01',
    selectionKey: 'act_iso_improve_grip',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้ภาชนะหรือด้ามจับที่จับได้ถนัดและมั่นคง',
    englishText: 'Use containers or handles that are easy to grip securely.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '79',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_job_rotation.01',
    selectionKey: 'act_iso_job_rotation',
    displayOrder: 1,
    category: 'restRotation',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'สลับงานเพื่อลดการใช้กล้ามเนื้อกลุ่มเดิมต่อเนื่องนานเกินไป',
    englishText: 'Rotate tasks so the same muscles are not used continuously.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '229',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_keep_load_close.01',
    selectionKey: 'act_iso_keep_load_close',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'วางของให้ชิดลำตัวก่อนยกหรือขนย้าย',
    englishText: 'Keep the load close to the body before lifting or carrying.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '51',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_lift_height.01',
    selectionKey: 'act_iso_lift_height',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'จัดของให้อยู่ระดับประมาณข้อนิ้วถึงข้อศอกก่อนยก',
    englishText:
        'Place the load around knuckle-to-elbow height before lifting.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '4',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_neutral_reach.01',
    selectionKey: 'act_iso_neutral_reach',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ทำงานใกล้ลำตัว',
    englishText: 'Keep hands near the body.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '51,65',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_neutral_reach.02',
    selectionKey: 'act_iso_neutral_reach',
    displayOrder: 2,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดการเอื้อมไกลหรือขยับข้อไปสุดช่วง',
    englishText: 'Avoid extreme reach or joint positions.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '51,65',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_plan_recovery.01',
    selectionKey: 'act_iso_plan_recovery',
    displayOrder: 1,
    category: 'restRotation',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'วางแผนพักสั้น ๆ หรือสลับงานเมื่อต้องทำซ้ำหลายรอบ',
    englishText:
        'Plan short recovery breaks or rotate tasks during repeated work.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '243',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_push_handle_height.01',
    selectionKey: 'act_iso_push_handle_height',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ปรับด้ามจับให้อยู่ใกล้ระดับข้อศอก เพื่อใช้แรงได้มั่นคง',
    englishText:
        'Adjust handles near elbow height so the body can push steadily.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '63',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_push_not_pull.01',
    selectionKey: 'act_iso_push_not_pull',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ถ้าทำได้ให้ดันโดยใช้น้ำหนักตัว แทนการลากด้วยแรงแขน',
    englishText:
        'Push with body weight when possible instead of pulling with the arms.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '5',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_push_smooth.01',
    selectionKey: 'act_iso_push_smooth',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ออกแรงดันหรือลากอย่างต่อเนื่อง ไม่กระชาก',
    englishText: 'Apply push or pull force smoothly without jerking.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '5',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_reduce_frequency.01',
    selectionKey: 'act_iso_reduce_frequency',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดความถี่ในการยก หรือแบ่งงานเป็นรอบสั้นลง',
    englishText:
        'Reduce lifting frequency or split the task into shorter rounds.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4,8',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_reduce_push_distance.01',
    selectionKey: 'act_iso_reduce_push_distance',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดระยะทางดัน/ลาก หรือแบ่งเส้นทางเป็นช่วงสั้นลง',
    englishText:
        'Shorten push/pull distance or divide the route into shorter sections.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '5',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_tool_handle_fit.01',
    selectionKey: 'act_iso_tool_handle_fit',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้ด้ามจับที่ไม่ลื่น มีขนาดพอดีมือ',
    englishText: 'Use non-slip handles that fit the hand.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '79',
  ),
  RecommendationCatalogItem(
    id: 'act_iso_tool_handle_fit.02',
    selectionKey: 'act_iso_tool_handle_fit',
    displayOrder: 2,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดแรงบีบจับ',
    englishText: 'Reduce gripping force.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '79',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_high.01',
    selectionKey: 'act_pesticide_ref_high',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText:
        'ถ้าถังพ่นหนักเกินน้ำหนักที่แนะนำ ให้ใช้อุปกรณ์ล้อเข็นหรือหัวฉีดแบบต่อท่อยาว',
    englishText:
        'If the sprayer tank exceeds the recommended weight, use a wheeled aid or a long-hose nozzle.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_high.02',
    selectionKey: 'act_pesticide_ref_high',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'หมุนเวียนงานกับเพื่อนทุก 30 นาที',
    englishText: 'Rotate tasks with a coworker every 30 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_low.01',
    selectionKey: 'act_pesticide_ref_low',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ปรับสายสะพายเครื่องพ่นให้พอดี',
    englishText: 'Fit sprayer straps properly.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_low.02',
    selectionKey: 'act_pesticide_ref_low',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ใช้หัวฉีดน้ำหนักเบา',
    englishText: 'Use a lightweight nozzle.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_low.03',
    selectionKey: 'act_pesticide_ref_low',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'พัก 5 นาทีทุกชั่วโมง',
    englishText: 'Rest 5 minutes every hour.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_medium.01',
    selectionKey: 'act_pesticide_ref_medium',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ลดระยะเวลาพ่นต่อเนื่องไม่เกิน 1 ชั่วโมง แล้วพัก 15 นาที',
    englishText:
        'Limit continuous spraying to 1 hour, then rest for 15 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pesticide_ref_medium.02',
    selectionKey: 'act_pesticide_ref_medium',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'pesticide',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'สลับข้างที่ถือท่อพ่น และใส่รองเท้ากันลื่น',
    englishText:
        'Alternate the side holding the spray wand and wear non-slip footwear.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_high.01',
    selectionKey: 'act_pruning_ref_high',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'เปลี่ยนมาใช้เครื่องตัดกิ่งแบบกลไกช่วย',
    englishText: 'Use mechanically assisted pruning tools.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_high.02',
    selectionKey: 'act_pruning_ref_high',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ถ้าใช้กรรไกรต้องพัก 10 นาทีทุก 20 นาที',
    englishText: 'When using shears, rest for 10 minutes every 20 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_high.03',
    selectionKey: 'act_pruning_ref_high',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ทำงานเป็นทีมเพื่อหมุนเวียน',
    englishText: 'Work as a team to rotate tasks.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_high.04',
    selectionKey: 'act_pruning_ref_high',
    displayOrder: 4,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'หลีกเลี่ยงการตัดในท่าบิดตัว',
    englishText: 'Avoid twisting while pruning.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_low.01',
    selectionKey: 'act_pruning_ref_low',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ใช้กรรไกรคมและน้ำหนักเบา',
    englishText: 'Use sharp, lightweight shears.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_low.02',
    selectionKey: 'act_pruning_ref_low',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'สลับแขนทุก 10-15 นาที และอย่ายกแขนเหนือศีรษะนาน',
    englishText:
        'Switch arms every 10-15 minutes and avoid keeping the arms above the head for long periods.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_medium.01',
    selectionKey: 'act_pruning_ref_medium',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ใช้กรรไกรแบบก้านยาวเพื่อลดการเอื้อม',
    englishText: 'Use long-handled shears to reduce reaching.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_medium.02',
    selectionKey: 'act_pruning_ref_medium',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ใช้บันไดสำหรับกิ่งสูง',
    englishText: 'Use a ladder for high branches.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_medium.03',
    selectionKey: 'act_pruning_ref_medium',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'สลับแขน',
    englishText: 'Switch arms.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_pruning_ref_medium.04',
    selectionKey: 'act_pruning_ref_medium',
    displayOrder: 4,
    category: 'riskReduction',
    activity: 'pruning',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'พัก 5 นาทีทุก 30 นาที',
    englishText: 'Rest 5 minutes every 30 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_reduce_arm_raise.01',
    selectionKey: 'act_reduce_arm_raise',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดการยกแขนสูงเหนือไหล่เป็นเวลานาน',
    englishText: 'Reduce prolonged arm raising.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4-5',
  ),
  RecommendationCatalogItem(
    id: 'act_reduce_load_tool.01',
    selectionKey: 'act_reduce_load_tool',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดน้ำหนักสิ่งของ หรือใช้เครื่องทุ่นแรง',
    englishText: 'Reduce the load weight or use a handling aid.',
    sourceId: 'body_map_recommendations',
    sourcePage: '4,8',
  ),
  RecommendationCatalogItem(
    id: 'act_reduce_weight.01',
    selectionKey: 'act_reduce_weight',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ลดน้ำหนักที่ยก',
    englishText: 'Reduce load weight.',
    sourceId: 'body_map_recommendations',
    sourcePage: '7-8',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_high.01',
    selectionKey: 'act_ref_weight_high',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'ลดน้ำหนักที่ยกทันที: ชาย 20-45 ปี ไม่เกิน 13 กก.',
    englishText:
        'Reduce lifting weight immediately: men aged 20-45 years should lift no more than 13 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_high.02',
    selectionKey: 'act_ref_weight_high',
    displayOrder: 2,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'ชายอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 10 กก.',
    englishText:
        'Men under 20 or over 45 years should lift no more than 10 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_high.03',
    selectionKey: 'act_ref_weight_high',
    displayOrder: 3,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'หญิง 20-45 ปี ไม่เกิน 10 กก.',
    englishText: 'Women aged 20-45 years should lift no more than 10 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_high.04',
    selectionKey: 'act_ref_weight_high',
    displayOrder: 4,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'หญิงอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 8 กก.',
    englishText:
        'Women under 20 or over 45 years should lift no more than 8 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_high.05',
    selectionKey: 'act_ref_weight_high',
    displayOrder: 5,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'high',
    thaiText: 'ถ้าเกินนี้ให้ใช้อุปกรณ์ช่วย',
    englishText: 'Use a handling aid if the load exceeds these limits.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_low.01',
    selectionKey: 'act_ref_weight_low',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'low',
    thaiText: 'ตรวจสอบน้ำหนักที่ยก: ชาย 20-45 ปี ไม่เกิน 25 กก.',
    englishText:
        'Check lifting weight: men aged 20-45 years should lift no more than 25 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_low.02',
    selectionKey: 'act_ref_weight_low',
    displayOrder: 2,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'low',
    thaiText: 'ชายอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 20 กก.',
    englishText:
        'Men under 20 or over 45 years should lift no more than 20 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_low.03',
    selectionKey: 'act_ref_weight_low',
    displayOrder: 3,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'low',
    thaiText: 'หญิง 20-45 ปี ไม่เกิน 20 กก.',
    englishText: 'Women aged 20-45 years should lift no more than 20 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_low.04',
    selectionKey: 'act_ref_weight_low',
    displayOrder: 4,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'low',
    thaiText: 'หญิงอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 15 กก.',
    englishText:
        'Women under 20 or over 45 years should lift no more than 15 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_medium.01',
    selectionKey: 'act_ref_weight_medium',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'ปรับน้ำหนักที่ยก: ชาย 20-45 ปี ไม่เกิน 18 กก.',
    englishText:
        'Reduce lifting weight: men aged 20-45 years should lift no more than 18 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_medium.02',
    selectionKey: 'act_ref_weight_medium',
    displayOrder: 2,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'ชายอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 15 กก.',
    englishText:
        'Men under 20 or over 45 years should lift no more than 15 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_medium.03',
    selectionKey: 'act_ref_weight_medium',
    displayOrder: 3,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'หญิง 20-45 ปี ไม่เกิน 15 กก.',
    englishText: 'Women aged 20-45 years should lift no more than 15 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_ref_weight_medium.04',
    selectionKey: 'act_ref_weight_medium',
    displayOrder: 4,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'manual',
    riskLevel: 'medium',
    thaiText: 'หญิงอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 11 กก.',
    englishText:
        'Women under 20 or over 45 years should lift no more than 11 kg.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_rest_stretch.01',
    selectionKey: 'act_rest_stretch',
    displayOrder: 1,
    category: 'restRotation',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ควรพักเบรกเพื่อยืดเหยียดกล้ามเนื้อ',
    englishText: 'Take breaks to stretch muscles.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '243',
  ),
  RecommendationCatalogItem(
    id: 'act_spray_extension.01',
    selectionKey: 'act_spray_extension',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้ด้ามต่อหัวพ่น เพื่อลดการยกแขนสูงหรือเอื้อมไกล',
    englishText:
        'Use an extension wand so the arm does not stay raised or overreached.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '2',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_low_stool.01',
    selectionKey: 'act_transplant_low_stool',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้เก้าอี้เตี้ยหรือเบาะรองเข่า แทนการนั่งยองนาน ๆ',
    englishText:
        'Use a low stool or knee pad instead of squatting for long periods.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_raise_bed.01',
    selectionKey: 'act_transplant_raise_bed',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ยกถาดกล้าหรือพื้นที่ทำงานให้สูงขึ้น เพื่อลดการก้มหลังลึก',
    englishText: 'Raise seedling trays or work height to reduce deep bending.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_high.01',
    selectionKey: 'act_transplant_ref_high',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ปรับปรุงทันทีโดยยกแปลงเพาะชำให้สูงระดับเอว',
    englishText:
        'Improve the task immediately by raising the seedling bed to waist height.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_high.02',
    selectionKey: 'act_transplant_ref_high',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ใช้อุปกรณ์นั่งยองหรือเก้าอี้เตี้ย',
    englishText: 'Use a squatting support or low stool.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_high.03',
    selectionKey: 'act_transplant_ref_high',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'พักทุก 15-20 นาที',
    englishText: 'Take a break every 15-20 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_low.01',
    selectionKey: 'act_transplant_ref_low',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ท่าทางดีอยู่แล้ว ควรสลับยืนกับนั่งยองทุก 20 นาที',
    englishText:
        'The posture is acceptable; alternate between standing and squatting every 20 minutes.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_low.02',
    selectionKey: 'act_transplant_ref_low',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ตรวจสอบความสูงของแปลงเพาะชำให้พอดีกับเอว',
    englishText: 'Check that the seedling bed is close to waist height.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_medium.01',
    selectionKey: 'act_transplant_ref_medium',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ลดการก้มโดยยกแปลงเพาะชำให้สูงขึ้น',
    englishText: 'Raise the seedling bed to reduce bending.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_medium.02',
    selectionKey: 'act_transplant_ref_medium',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ใช้เบาะรองนั่งยองหรือเก้าอี้เตี้ย',
    englishText: 'Use a squatting cushion or low stool.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transplant_ref_medium.03',
    selectionKey: 'act_transplant_ref_medium',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'transplanting',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'สลับท่าทุก 15 นาที และฝึกยกต้นกล้าโดยใช้ขา',
    englishText:
        'Change posture every 15 minutes and lift seedlings using the legs.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_clear_path.01',
    selectionKey: 'act_transport_clear_path',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'จัดทางเดินให้เรียบและไม่มีสิ่งกีดขวางก่อนขนย้าย',
    englishText:
        'Make the transport path level and clear of obstacles before moving materials.',
    sourceId: 'ilo_ergonomic_checkpoints_agriculture',
    sourcePage: '29',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_high.01',
    selectionKey: 'act_transport_ref_high',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ลดน้ำหนักกระสอบ',
    englishText: 'Reduce sack weight.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_high.02',
    selectionKey: 'act_transport_ref_high',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText: 'ใช้เกวียนหรือรถเข็นล้อใหญ่ ปูพื้นกันลื่น',
    englishText:
        'Use a wagon or large-wheel cart and provide a non-slip surface.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_high.03',
    selectionKey: 'act_transport_ref_high',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'high',
    thaiText:
        'จัดพัก 10-15 นาทีทุก 30 นาที และฝึกเทคนิคการยกที่ถูกต้องร่วมกับเพื่อน',
    englishText:
        'Rest for 10-15 minutes every 30 minutes and practise correct team-lifting technique.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_low.01',
    selectionKey: 'act_transport_ref_low',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ใช้รถเข็นทุกครั้ง',
    englishText: 'Use a cart every time.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_low.02',
    selectionKey: 'act_transport_ref_low',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'low',
    thaiText: 'ยกของโดยงอเข่า หลังตรง ไม่บิดตัว และสวมรองเท้ากันลื่น',
    englishText:
        'Lift by bending the knees, keeping the back straight, avoiding twisting, and wearing non-slip footwear.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_medium.01',
    selectionKey: 'act_transport_ref_medium',
    displayOrder: 1,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ลดน้ำหนักกระสอบ',
    englishText: 'Reduce sack weight.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_medium.02',
    selectionKey: 'act_transport_ref_medium',
    displayOrder: 2,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ใช้รถเข็น',
    englishText: 'Use a cart.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_medium.03',
    selectionKey: 'act_transport_ref_medium',
    displayOrder: 3,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'ปรับปรุงทางเดิน',
    englishText: 'Improve the path.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_ref_medium.04',
    selectionKey: 'act_transport_ref_medium',
    displayOrder: 4,
    category: 'riskReduction',
    activity: 'transport',
    bodyPart: 'any',
    riskLevel: 'medium',
    thaiText: 'เปลี่ยนทิศทางโดยหมุนเท้าแทนการบิดเอว',
    englishText: 'Turn with the feet instead of twisting the waist.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '3',
  ),
  RecommendationCatalogItem(
    id: 'act_transport_two_person.01',
    selectionKey: 'act_transport_two_person',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ให้คนช่วยยกเมื่อผลผลิตหนักเกินไป',
    englishText: 'Ask another person to help lift heavy produce when needed.',
    sourceId: 'body_map_recommendations',
    sourcePage: '8',
  ),
  RecommendationCatalogItem(
    id: 'act_use_cart_distance.01',
    selectionKey: 'act_use_cart_distance',
    displayOrder: 1,
    category: 'workloadSupport',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้รถเข็นหรืออุปกรณ์ช่วยขนย้ายเมื่อต้องขนไกล',
    englishText: 'Use a cart or handling aid for long distance transport.',
    sourceId: 'body_map_recommendations',
    sourcePage: '3,8',
  ),
  RecommendationCatalogItem(
    id: 'act_use_legs.01',
    selectionKey: 'act_use_legs',
    displayOrder: 1,
    category: 'posture',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ใช้แรงจากขาในการออกแรง ไม่ใช่หลัง',
    englishText: 'Use force from the legs, not the back.',
    sourceId: 'app_recommendations_v3',
    sourcePage: '1,3',
  ),
  RecommendationCatalogItem(
    id: 'report.selected_recommendations',
    selectionKey: 'report.selected_recommendations',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'คำแนะนำที่เลือก',
    englishText: 'Selected recommendations',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'system.unmapped_saved_recommendation',
    selectionKey: 'system.unmapped_saved_recommendation',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ไม่สามารถจับคู่คำแนะนำเดิมกับรายการปัจจุบันได้',
    englishText:
        'A saved recommendation could not be matched to the current approved catalog.',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.category.posture',
    selectionKey: 'ui.category.posture',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ท่าทางที่ควรปรับ',
    englishText: 'Posture to adjust',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.category.rest_rotation',
    selectionKey: 'ui.category.rest_rotation',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'การพักหรือสลับงาน',
    englishText: 'Rest or task rotation',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.category.risk_reduction',
    selectionKey: 'ui.category.risk_reduction',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'วิธีลดความเสี่ยง',
    englishText: 'Ways to reduce risk',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.category.workload_support',
    selectionKey: 'ui.category.workload_support',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'อุปกรณ์ช่วยลดภาระงาน',
    englishText: 'Tools or workload support',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.recommendations.empty',
    selectionKey: 'ui.recommendations.empty',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'ไม่มีคำแนะนำเพิ่มเติม',
    englishText: 'No additional recommendation',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.recommendations.full',
    selectionKey: 'ui.recommendations.full',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'คำแนะนำฉบับเต็ม',
    englishText: 'Full recommendations',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.recommendations.heading',
    selectionKey: 'ui.recommendations.heading',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'คำแนะนำตามกิจกรรมและความเสี่ยง',
    englishText: 'Recommendations by activity and risk',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
  RecommendationCatalogItem(
    id: 'ui.recommendations.instruction',
    selectionKey: 'ui.recommendations.instruction',
    displayOrder: 1,
    category: 'interface',
    activity: 'any',
    bodyPart: 'any',
    riskLevel: 'any',
    thaiText: 'เริ่มจากข้อที่ทำได้จริงในงานนี้ แล้วติดตามคะแนนครั้งถัดไป',
    englishText:
        'Start with actions that fit this task, then compare the next result.',
    sourceId: 'current_app_recommendation_copy',
    sourcePage: '',
  ),
];

const generatedRecommendationLegacyAliases = <String, String>{
  'Adjust handles near elbow height so the body can push steadily':
      'act_iso_push_handle_height',
  'Adjust sprayer straps tightly': 'act_extra_spray_strap',
  'Adjust work to eye level': 'act_adj_eye_level',
  'Ask another person to help lift heavy produce when needed':
      'act_transport_two_person',
  'Avoid bending for more than 10-15 minutes, stretch every 15 minutes, face the load before lifting, and turn with the feet instead of twisting the waist.':
      'act_body_trunk_high',
  'Avoid deep bending or use back support': 'act_avoid_bend',
  'Avoid squatting or kneeling for more than 10 minutes, rest every 10-15 minutes, use floor-work aids, and reduce time working near the ground.':
      'act_body_legs_very_high',
  'Avoid twisting or side bending while working': 'act_avoid_twist',
  'Change posture between standing and squatting every 20 minutes, use soft gloves, and place baskets on a raised stand.':
      'act_harvest_ref_low',
  'Change the work method immediately: lift materials to waist level, use long-handled tools, and change posture every 10-15 minutes.':
      'act_body_neck_very_high',
  'Check cart wheels for friction': 'act_check_wheels',
  'Check lifting weight: men 20-45 years up to 25 kg; men under 20 or over 45 up to 20 kg; women 20-45 up to 20 kg; women under 20 or over 45 up to 15 kg.':
      'act_ref_weight_low',
  'Clear the path and keep the walking surface even before transport':
      'act_transport_clear_path',
  'Do not keep arms above shoulder level for more than 2 minutes; rest 3-5 minutes every 15-20 minutes and use long-handled tools or a stable platform.':
      'act_body_arms_high',
  'Do not squat or kneel continuously for more than 15 minutes; walk 3-5 minutes every 15 minutes and use a low stool or knee pad.':
      'act_body_legs_high',
  'Empty the basket more often to reduce accumulated carrying load':
      'act_harvest_empty_often',
  'Fit sprayer straps properly, use a lightweight nozzle, and rest 5 minutes every hour.':
      'act_pesticide_ref_low',
  'If the sprayer tank exceeds the recommended weight, use a wheeled aid or long-hose nozzle and rotate with a coworker every 30 minutes.':
      'act_pesticide_ref_high',
  'Improve immediately: raise the seedling bed to waist level, use a low stool or squatting support, and rest every 15-20 minutes.':
      'act_transplant_ref_high',
  'Keep floors firm, level, dry, and clear of obstacles': 'act_iso_floor_level',
  'Keep hands near the body and avoid extreme reach or joint positions':
      'act_iso_neutral_reach',
  'Keep materials within 40 cm reach, put tools down when not in use, rest shoulders every 30 minutes, and keep work below shoulder height.':
      'act_body_arms_medium',
  'Keep materials within 40 cm, raise work from the ground by 50-70 cm, and stand up to change posture every 20-30 minutes.':
      'act_body_trunk_medium',
  'Keep the load close to the body before lifting or carrying':
      'act_iso_keep_load_close',
  'Keep wrist in neutral position': 'act_adj_wrist',
  'Limit continuous spraying to 1 hour, rest 15 minutes, switch the hand/side holding the wand, and wear non-slip footwear.':
      'act_pesticide_ref_medium',
  'Limit each load to no more than 10 kg, use a cart for distances over 10 m, ask for two-person lifting when over 20 kg, and avoid twisting while lifting.':
      'act_body_manual_high',
  'Limit overhead work to short rounds, use lighter long-handled tools, and rotate to work below shoulder level.':
      'act_body_arms_very_high',
  'Move closer to the plant before picking instead of overreaching':
      'act_harvest_move_closer',
  'Place the load around knuckle-to-elbow height before lifting':
      'act_iso_lift_height',
  'Plan short recovery breaks or rotate tasks during repeated work':
      'act_iso_plan_recovery',
  'Posture is acceptable. Alternate standing and squatting every 20 minutes and check seedling-bed height near waist level.':
      'act_transplant_ref_low',
  'Push or pull smoothly and avoid sudden jerking force': 'act_iso_push_smooth',
  'Push with body weight when possible instead of pulling with the arms':
      'act_iso_push_not_pull',
  'Raise seedling trays or work height to reduce deep bending':
      'act_transplant_raise_bed',
  'Raise the seedling bed to reduce bending, use a squat cushion or low stool, change posture every 15 minutes, and lift seedlings with the legs.':
      'act_transplant_ref_medium',
  'Raise the work area, stretch the neck every 15-20 minutes, use reach tools, and avoid twisting or tilting the neck.':
      'act_body_neck_high',
  'Raise trays or materials to waist height, change neck posture every 30 minutes, and avoid looking down continuously.':
      'act_body_neck_medium',
  'Reduce fertilizer weight per trip, use a conveyor or cart, rest 10 minutes every hour, and avoid continuous work on slopes.':
      'act_fert_ref_high',
  'Reduce lifting frequency or split the task into shorter rounds':
      'act_iso_reduce_frequency',
  'Reduce lifting weight immediately: men 20-45 years up to 13 kg; men under 20 or over 45 up to 10 kg; women 20-45 up to 10 kg; women under 20 or over 45 up to 8 kg. Use handling aids if heavier.':
      'act_ref_weight_high',
  'Reduce lifting weight: men 20-45 years up to 18 kg; men under 20 or over 45 up to 15 kg; women 20-45 up to 15 kg; women under 20 or over 45 up to 11 kg.':
      'act_ref_weight_medium',
  'Reduce load or use assist tools': 'act_reduce_load_tool',
  'Reduce load weight': 'act_reduce_weight',
  'Reduce prolonged arm raising': 'act_reduce_arm_raise',
  'Reduce sack weight, use a cart, improve the path, and turn with the feet instead of twisting the waist.':
      'act_transport_ref_medium',
  'Reduce sack weight, use a wagon or large-wheel cart, add non-slip flooring, rest 10-15 minutes every 30 minutes, and practice team lifting technique.':
      'act_transport_ref_high',
  'Rest hands and wrists every 15-20 minutes, rotate tasks every 20-30 minutes, use suitable handles, and reduce gripping force.':
      'act_body_wrists_high',
  'Rest wrists 3-5 minutes every 15 minutes, change to better-fitting tools, and use aids that reduce unnecessary gripping or squeezing force.':
      'act_body_wrists_very_high',
  'Rotate tasks so the same muscles are not used continuously':
      'act_iso_job_rotation',
  'Shorten push/pull distance or divide the route into shorter sections':
      'act_iso_reduce_push_distance',
  'Split each bag or container to no more than 15 kg, keep the load close to the body, lift with both hands, and avoid lifting above shoulder height.':
      'act_body_manual_medium',
  'Split fertilizer into smaller containers, use a cart, avoid twisting while lifting, and wear non-slip footwear.':
      'act_fert_ref_medium',
  'Split fertilizer into smaller loads per round': 'act_fert_split_load',
  'Stand or walk every 20 minutes, use a squat cushion or knee pad, and alternate between sitting, standing, and walking.':
      'act_body_legs_medium',
  'Switch shoulders to balance load': 'act_extra_spray_switch',
  'Take breaks to stretch muscles': 'act_rest_stretch',
  'Use a cart every time, lift by bending the knees with a straight back, avoid twisting, and wear non-slip footwear.':
      'act_transport_ref_low',
  'Use a cart or handling aid for long distance transport':
      'act_use_cart_distance',
  'Use a cart when fertilizer must be moved far, and change posture every 30 minutes.':
      'act_fert_ref_low',
  'Use a cart, trolley, or lifting aid; avoid lifting more than 20 kg alone, team-lift 20-25 kg loads, and use lifting equipment above 25 kg.':
      'act_body_manual_very_high',
  'Use a ladder for high branches, avoid climbing, rest 10 minutes every 20 minutes, and stop immediately if hand or back pain occurs.':
      'act_harvest_ref_high',
  'Use a low stool or knee pad instead of squatting for long periods':
      'act_transplant_low_stool',
  'Use an extension wand so the arm does not stay raised or overreached':
      'act_spray_extension',
  'Use cart instead of carrying sacks': 'act_extra_fert_cart',
  'Use carts or lifting aids, avoid lifting more than 20 kg alone, raise the work area to knee-to-waist height, and reduce unnecessary carries.':
      'act_body_trunk_very_high',
  'Use containers or handles that are easy to grip securely':
      'act_iso_improve_grip',
  'Use handles that fit the hand, relax the grip regularly, rest wrists every 30 minutes, and stretch fingers and wrists during breaks.':
      'act_body_wrists_medium',
  'Use leg muscles, not back': 'act_use_legs',
  'Use long-handled pruning shears': 'act_extra_prune_tool',
  'Use long-handled shears to reduce reaching, use a ladder for high branches, switch arms, and rest 5 minutes every 30 minutes.':
      'act_pruning_ref_medium',
  'Use mechanical pruning tools when possible. If shears are used, rest 10 minutes every 20 minutes, rotate as a team, and avoid twisting while cutting.':
      'act_pruning_ref_high',
  'Use padded gloves, reduce bending by raising the basket, rest 5 minutes every 30 minutes, and watch for hand numbness.':
      'act_harvest_ref_medium',
  'Use padded, non-slip tool handles sized for a secure grip':
      'act_iso_tool_handle_fit',
  'Use sharp lightweight shears, switch arms every 10-15 minutes, and avoid keeping arms above the head for long periods.':
      'act_pruning_ref_low',
  'Use stable ladder instead of reaching': 'act_extra_prune_ladder',
  'ขยับเข้าใกล้ต้นก่อนเก็บ เพื่อลดการเอื้อมไกล': 'act_harvest_move_closer',
  'ควรพักเบรกเพื่อยืดเหยียดกล้ามเนื้อ': 'act_rest_stretch',
  'จัดของให้อยู่ระดับประมาณข้อนิ้วถึงข้อศอกก่อนยก': 'act_iso_lift_height',
  'จัดทางเดินให้เรียบและไม่มีสิ่งกีดขวางก่อนขนย้าย': 'act_transport_clear_path',
  'จัดพื้นทางเดินให้เรียบ แห้ง ไม่ลื่น และไม่มีสิ่งกีดขวาง':
      'act_iso_floor_level',
  'จัดวัสดุให้อยู่ในระยะเอื้อมไม่เกิน 40 ซม. วางอุปกรณ์เมื่อไม่ใช้ พักไหล่ทุก 30 นาที และให้งานอยู่ต่ำกว่าระดับไหล่':
      'act_body_arms_medium',
  'จำกัดงานเหนือศีรษะเป็นรอบสั้น ใช้เครื่องมือด้ามยาวที่น้ำหนักเบา และสลับไปทำงานที่ใช้แขนต่ำกว่าระดับไหล่':
      'act_body_arms_very_high',
  'ตรวจสอบน้ำหนักที่ยก: ชาย 20-45 ปี ไม่เกิน 25 กก.; ชายอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 20 กก.; หญิง 20-45 ปี ไม่เกิน 20 กก.; หญิงอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 15 กก.':
      'act_ref_weight_low',
  'ตรวจสอบล้อรถเข็นว่าฝืดหรือไม่': 'act_check_wheels',
  'ถ้าถังพ่นหนักเกินน้ำหนักที่แนะนำ ให้ใช้อุปกรณ์ล้อเข็นหรือหัวฉีดแบบต่อท่อยาว และหมุนเวียนงานกับเพื่อนทุก 30 นาที':
      'act_pesticide_ref_high',
  'ถ้าทำได้ให้ดันโดยใช้น้ำหนักตัว แทนการลากด้วยแรงแขน': 'act_iso_push_not_pull',
  'ถ้าเก็บผลจากกิ่งสูงต้องใช้บันได หลีกเลี่ยงการปีน หยุดพัก 10 นาทีทุก 20 นาที และถ้ามีอาการปวดมือหรือหลังให้หยุดงานทันที':
      'act_harvest_ref_high',
  'ทำงานใกล้ลำตัว ลดการเอื้อมไกลหรือขยับข้อไปสุดช่วง': 'act_iso_neutral_reach',
  'ท่าทางดีอยู่แล้ว ควรสลับยืนกับนั่งยองทุก 20 นาที และตรวจสอบความสูงของแปลงเพาะชำให้พอดีกับเอว':
      'act_transplant_ref_low',
  'ปรับงานให้อยู่ระดับสายตา ลดการก้มคอ': 'act_adj_eye_level',
  'ปรับด้ามจับเครื่องมือให้ข้อมืออยู่ในแนวตรง': 'act_adj_wrist',
  'ปรับด้ามจับให้อยู่ใกล้ระดับข้อศอก เพื่อใช้แรงได้มั่นคง':
      'act_iso_push_handle_height',
  'ปรับน้ำหนักที่ยก: ชาย 20-45 ปี ไม่เกิน 18 กก.; ชายอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 15 กก.; หญิง 20-45 ปี ไม่เกิน 15 กก.; หญิงอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 11 กก.':
      'act_ref_weight_medium',
  'ปรับปรุงทันที: ยกแปลงเพาะชำให้สูงระดับเอว ใช้อุปกรณ์นั่งยองหรือเก้าอี้เตี้ย และพักทุก 15-20 นาที':
      'act_transplant_ref_high',
  'ปรับพื้นที่ทำงานให้สูงขึ้น ยืดเหยียดคอทุก 15-20 นาที ใช้อุปกรณ์ช่วยหยิบจับ และหลีกเลี่ยงการบิดหรือเอียงคอ':
      'act_body_neck_high',
  'ปรับวิธีทำงานทันที ยกวัสดุขึ้นระดับเอว ใช้เครื่องมือด้ามยาว และเปลี่ยนอิริยาบถทุก 10-15 นาที':
      'act_body_neck_very_high',
  'ปรับสายสะพายเครื่องพ่นยาให้กระชับ': 'act_extra_spray_strap',
  'ปรับสายสะพายเครื่องพ่นให้พอดี ใช้หัวฉีดน้ำหนักเบา และพัก 5 นาทีทุกชั่วโมง':
      'act_pesticide_ref_low',
  'พักข้อมือ 3-5 นาทีทุก 15 นาที เปลี่ยนเครื่องมือให้พอดีกับมือ และใช้อุปกรณ์ช่วยลดแรงกำหรือแรงบีบที่ไม่จำเป็น':
      'act_body_wrists_very_high',
  'พักมือและข้อมือทุก 15-20 นาที สลับงานทุก 20-30 นาที ใช้ด้ามจับที่เหมาะสม และลดแรงกำขณะจับอุปกรณ์':
      'act_body_wrists_high',
  'ยกถาดกล้าหรือพื้นที่ทำงานให้สูงขึ้น เพื่อลดการก้มหลังลึก':
      'act_transplant_raise_bed',
  'ยกถาดหรือวัสดุให้อยู่ระดับเอว เปลี่ยนท่าคอทุก 30 นาที และหลีกเลี่ยงการก้มมองพื้นต่อเนื่อง':
      'act_body_neck_medium',
  'ลดการก้มโดยยกแปลงเพาะชำให้สูงขึ้น ใช้เบาะรองนั่งยองหรือเก้าอี้เตี้ย สลับท่าทุก 15 นาที และฝึกยกต้นกล้าโดยใช้ขา':
      'act_transplant_ref_medium',
  'ลดการยกแขนสูงเหนือไหล่เป็นเวลานาน': 'act_reduce_arm_raise',
  'ลดความถี่ในการยก หรือแบ่งงานเป็นรอบสั้นลง': 'act_iso_reduce_frequency',
  'ลดน้ำหนักกระสอบ ใช้รถเข็น ปรับปรุงทางเดิน และเปลี่ยนทิศทางโดยหมุนเท้าแทนการบิดเอว':
      'act_transport_ref_medium',
  'ลดน้ำหนักกระสอบ ใช้เกวียนหรือรถเข็นล้อใหญ่ ปูพื้นกันลื่น จัดพัก 10-15 นาทีทุก 30 นาที และฝึกเทคนิคการยกที่ถูกต้องร่วมกับเพื่อน':
      'act_transport_ref_high',
  'ลดน้ำหนักที่ยก': 'act_reduce_weight',
  'ลดน้ำหนักที่ยกทันที: ชาย 20-45 ปี ไม่เกิน 13 กก.; ชายอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 10 กก.; หญิง 20-45 ปี ไม่เกิน 10 กก.; หญิงอายุต่ำกว่า 20 หรือมากกว่า 45 ปี ไม่เกิน 8 กก. ถ้าเกินนี้ให้ใช้อุปกรณ์ช่วย':
      'act_ref_weight_high',
  'ลดน้ำหนักปุ๋ยต่อครั้ง ใช้สายพานหรือรถเข็น จัดพัก 10 นาทีทุกชั่วโมง และหลีกเลี่ยงการทำงานบนพื้นที่ลาดชันต่อเนื่อง':
      'act_fert_ref_high',
  'ลดน้ำหนักสิ่งของ หรือใช้เครื่องทุ่นแรง': 'act_reduce_load_tool',
  'ลดระยะทางดัน/ลาก หรือแบ่งเส้นทางเป็นช่วงสั้นลง':
      'act_iso_reduce_push_distance',
  'ลดระยะเวลาพ่นต่อเนื่องไม่เกิน 1 ชั่วโมง แล้วพัก 15 นาที สลับข้างที่ถือท่อพ่น และใส่รองเท้ากันลื่น':
      'act_pesticide_ref_medium',
  'ลุกยืนหรือเดินทุก 20 นาที ใช้เบาะรองนั่งหรือแผ่นรองเข่า และสลับระหว่างนั่ง ยืน และเดิน':
      'act_body_legs_medium',
  'วางของให้ชิดลำตัวก่อนยกหรือขนย้าย': 'act_iso_keep_load_close',
  'วางวัสดุให้อยู่ใกล้ตัวไม่เกิน 40 ซม. ยกงานจากพื้น 50-70 ซม. และลุกเปลี่ยนท่าทุก 20-30 นาที':
      'act_body_trunk_medium',
  'วางแผนพักสั้น ๆ หรือสลับงานเมื่อต้องทำซ้ำหลายรอบ': 'act_iso_plan_recovery',
  'สลับข้างสะพายถังเพื่อลดการกดทับไหล่เดียว': 'act_extra_spray_switch',
  'สลับงานเพื่อลดการใช้กล้ามเนื้อกลุ่มเดิมต่อเนื่องนานเกินไป':
      'act_iso_job_rotation',
  'หลีกเลี่ยงการก้มต่อเนื่องเกิน 10-15 นาที ยืดเหยียดทุก 15 นาที หันหน้าเข้าหาวัสดุก่อนยก และหมุนเท้าแทนการบิดเอว':
      'act_body_trunk_high',
  'หลีกเลี่ยงการก้มหลังมาก หรือใช้เข็มขัดพยุงหลัง': 'act_avoid_bend',
  'หลีกเลี่ยงการนั่งยองหรือคุกเข่าเกิน 10 นาที พักทุก 10-15 นาที ใช้อุปกรณ์ช่วยทำงานระดับพื้น และลดเวลาทำงานใกล้พื้น':
      'act_body_legs_very_high',
  'หลีกเลี่ยงการบิดลำตัวหรือเอียงตัวขณะทำงาน': 'act_avoid_twist',
  'ออกแรงดันหรือลากอย่างต่อเนื่อง ไม่กระชาก': 'act_iso_push_smooth',
  'เทผลผลิตออกจากตะกร้าให้บ่อยขึ้น เพื่อลดน้ำหนักสะสม':
      'act_harvest_empty_often',
  'เปลี่ยนท่า ยืน-นั่งยอง ทุก 20 นาที ใช้ถุงมือนุ่ม และตั้งตะกร้าบนแท่นสูง':
      'act_harvest_ref_low',
  'เปลี่ยนมาใช้เครื่องตัดกิ่งแบบกลไกช่วย ถ้าใช้กรรไกรต้องพัก 10 นาทีทุก 20 นาที ทำงานเป็นทีมเพื่อหมุนเวียน และหลีกเลี่ยงการตัดในท่าบิดตัว':
      'act_pruning_ref_high',
  'แบ่งถุงหรือภาชนะให้หนักไม่เกิน 15 กก. ถือของให้ชิดลำตัว ใช้สองมือช่วยยก และหลีกเลี่ยงการยกเหนือระดับไหล่':
      'act_body_manual_medium',
  'แบ่งน้ำหนักต่อครั้งไม่เกิน 10 กก. ใช้รถเข็นเมื่อขนไกลกว่า 10 เมตร ให้ 2 คนช่วยยกเมื่อหนักเกิน 20 กก. และหลีกเลี่ยงการบิดตัวขณะยก':
      'act_body_manual_high',
  'แบ่งปุ๋ยเป็นน้ำหนักน้อยลงในแต่ละรอบ': 'act_fert_split_load',
  'แบ่งปุ๋ยใส่ภาชนะเล็ก ใช้รถเข็น หลีกเลี่ยงการบิดตัวขณะยก และใส่รองเท้ากันลื่น':
      'act_fert_ref_medium',
  'ใช้กรรไกรคมและน้ำหนักเบา สลับแขนทุก 10-15 นาที และอย่ายกแขนเหนือศีรษะนาน':
      'act_pruning_ref_low',
  'ใช้กรรไกรตัดกิ่งด้ามยาว': 'act_extra_prune_tool',
  'ใช้กรรไกรแบบก้านยาวเพื่อลดการเอื้อม ใช้บันไดสำหรับกิ่งสูง สลับแขน และพัก 5 นาทีทุก 30 นาที':
      'act_pruning_ref_medium',
  'ใช้ด้ามจับที่พอดีมือ คลายมือเป็นระยะ พักข้อมือทุก 30 นาที และยืดเหยียดนิ้วมือกับข้อมือระหว่างพัก':
      'act_body_wrists_medium',
  'ใช้ด้ามจับที่ไม่ลื่น มีขนาดพอดีมือ และลดแรงบีบจับ':
      'act_iso_tool_handle_fit',
  'ใช้ด้ามต่อหัวพ่น เพื่อลดการยกแขนสูงหรือเอื้อมไกล': 'act_spray_extension',
  'ใช้ถุงมือลดแรงกด ลดการก้มโดยปรับความสูงตะกร้า พัก 5 นาทีทุก 30 นาที และสังเกตอาการชาที่มือ':
      'act_harvest_ref_medium',
  'ใช้บันไดที่มั่นคงแทนการเอื้อมสุดแขน': 'act_extra_prune_ladder',
  'ใช้ภาชนะหรือด้ามจับที่จับได้ถนัดและมั่นคง': 'act_iso_improve_grip',
  'ใช้รถเข็น รถลาก หรืออุปกรณ์ช่วยยก หลีกเลี่ยงการยกเกิน 20 กก. คนเดียว ถ้าหนัก 20-25 กก. ให้ช่วยกันยก และถ้าเกิน 25 กก. ให้ใช้อุปกรณ์ช่วย':
      'act_body_manual_very_high',
  'ใช้รถเข็นถ้าต้องเคลื่อนย้ายปุ๋ยไกล และหมั่นเปลี่ยนท่าทางทุก 30 นาที':
      'act_fert_ref_low',
  'ใช้รถเข็นทุกครั้ง ยกของโดยงอเข่า หลังตรง ไม่บิดตัว และสวมรองเท้ากันลื่น':
      'act_transport_ref_low',
  'ใช้รถเข็นบรรทุกกระสอบปุ๋ยแทนการแบก': 'act_extra_fert_cart',
  'ใช้รถเข็นหรืออุปกรณ์ช่วยขนย้ายเมื่อต้องขนไกล': 'act_use_cart_distance',
  'ใช้รถเข็นหรืออุปกรณ์ช่วยยก หลีกเลี่ยงการยกเกิน 20 กก. คนเดียว ปรับงานให้อยู่ระดับเข่าถึงเอว และลดการขนย้ายที่ไม่จำเป็น':
      'act_body_trunk_very_high',
  'ใช้เก้าอี้เตี้ยหรือเบาะรองเข่า แทนการนั่งยองนาน ๆ':
      'act_transplant_low_stool',
  'ใช้แรงจากขาในการออกแรง ไม่ใช่หลัง': 'act_use_legs',
  'ให้คนช่วยยกเมื่อผลผลิตหนักเกินไป': 'act_transport_two_person',
  'ไม่นั่งยองหรือคุกเข่าต่อเนื่องเกิน 15 นาที ลุกเดิน 3-5 นาทีทุก 15 นาที และใช้เก้าอี้เตี้ยหรือแผ่นรองเข่า':
      'act_body_legs_high',
  'ไม่ยกแขนเหนือไหล่ต่อเนื่องเกิน 2 นาที พักแขน 3-5 นาทีทุก 15-20 นาที และใช้เครื่องมือด้ามยาวหรือแท่นยืนที่มั่นคง':
      'act_body_arms_high',
};
