import fs from 'node:fs/promises'; import path from 'node:path'; import crypto from 'node:crypto';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
const ROOT=process.env.FSOOKTA_HANDOVER_ROOT||'/private/tmp/fsookta-final-handover', OUT=path.join(ROOT,'artifacts','10_Knowledge_Transfer_Deck.pptx'), RENDER=path.join(ROOT,'renders','task7','deck');
const P=Presentation.create({slideSize:{width:1280,height:720}}), C={ink:'#000000',panel:'#EDEDED',rule:'#B8BCC4',blue:'#3D8DFF',white:'#FFFFFF'};
async function hash(r){return crypto.createHash('sha256').update(await fs.readFile(path.join(ROOT,r))).digest('hex')}
const SOURCE='evidence/task7-source';
async function cited(r,s='1.3.11+28'){return `${r} | ${await hash(r)} | ${s}`}
const sources={repo:await cited(`${SOURCE}/pubspec.yaml`),arch:await cited(`${SOURCE}/lib/app/sookta_app.dart`),data:await cited(`${SOURCE}/lib/app/app_state.dart`),export:await cited(`${SOURCE}/lib/core/services/assessment_export_service.dart`),ai:await cited('artifacts/04_AI_Algorithm_and_Model_Technical_Report.docx','controlled draft'),test:await cited('evidence/flutter_test_1.3.11+28.log'),uat:await cited('artifacts/08_UAT_Field_Test_and_Usability_Package.xlsx','historical'),sec:await cited('manifests/task7_offline_security_inspection.json','controlled draft'),minutes:await cited('artifacts/10_Knowledge_Transfer_Minutes.docx','controlled draft')};
function box(s,n,x,y,w,h,f=C.panel,l=C.rule){return s.shapes.add({geometry:'rect',name:n,position:{left:x,top:y,width:w,height:h},fill:f,line:{style:'solid',fill:l,width:1}})}
function text(s,n,v,x,y,w,h,z=22,b=false,c=C.ink,a='left'){const q=s.shapes.add({geometry:'textbox',name:n,position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});q.text=v;q.text.style={fontSize:z,typeface:'Helvetica Neue',bold:b,color:c,alignment:a,verticalAlignment:'top'};return q}
function title(s,v,n){text(s,'slide-title',v,42,28,1140,76,48,true);text(s,'slide-no',String(n).padStart(2,'0'),1184,660,54,22,16,false,C.ink,'right')}
function notes(s,a){s.speakerNotes.textFrame.setText(`[Sources]\n${a.join('\n')}\n[/Sources]\nPresenter note: pending human actions remain pending.`);s.speakerNotes.setVisible(false)}
function cover(){const s=P.slides.add();s.background.fill=C.white;box(s,'codex-grid-layout-library#slide-08-media',660,42,580,588,'#EAF5FB');text(s,'cover-title','SookTa\nKnowledge Transfer',42,48,570,230,68,true);text(s,'cover-body','Final handover baseline\n1.3.11+28\n\nSource-grounded architecture, data, algorithm, release and ownership guidance.',42,330,540,210,22);text(s,'cover-accent','TECHNICAL HANDOVER',714,100,440,52,32,true,C.blue);text(s,'cover-right','Full-history repository is authoritative\n\nLocal-first assessment\nDeterministic reference rules\nBundled model assistance\nOptional telemetry, default-off',714,190,440,310,22);text(s,'slide-no','01',1184,660,54,22,16,false,C.ink,'right');notes(s,[sources.repo,sources.arch])}
function metrics(n,t,i,a,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);text(s,'intro',i,42,118,1160,120,22);a.forEach((v,j)=>{const x=42+j*411;box(s,`codex-grid-layout-library#slide-19-panel-${j+1}`,x,318,374,310);text(s,`stat-${j+1}`,v[0],x+32,354,310,116,48,true,C.blue);text(s,`stat-body-${j+1}`,v[1],x+32,505,310,92,22)});notes(s,src)}
function timeline(n,t,a,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);box(s,'codex-grid-layout-library#slide-17-rule',36,354,1200,2,C.ink,C.ink);a.forEach((v,j)=>{const x=42+j*400;box(s,`node-${j+1}`,x,346,14,14,C.ink,C.ink);text(s,`label-${j+1}`,v[0],x,282,330,58,32,true);text(s,`body-${j+1}`,v[1],x,400,330,190,22)});notes(s,src)}
function evidence(n,t,i,a,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);text(s,'intro',i,42,112,1160,90,22);a.forEach((v,j)=>{const y=228+j*62;box(s,`codex-grid-layout-library#slide-14-row-${j+1}`,42,y,1196,56,j===0?'#D0EDFA':(j%2?'#FFFFFF':'#F5F5F5'));text(s,`c1-${j}`,v[0],58,y+7,260,44,22,j===0);text(s,`c2-${j}`,v[1],330,y+7,450,44,22,j===0);text(s,`c3-${j}`,v[2],795,y+7,425,44,22,j===0)});notes(s,src)}
function split(n,t,lt,lb,rt,rb,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);text(s,'left-title',lt,42,188,530,58,32,true);text(s,'left-body',lb,42,262,540,340,22);box(s,'codex-grid-layout-library#slide-08-media',658,164,580,466,'#EAF5FB');text(s,'right-title',rt,700,208,490,62,32,true,C.blue);text(s,'right-body',rb,700,292,490,280,22);notes(s,src)}
cover();
metrics(2,'Technical baseline ready; acceptance pending','The baseline is frozen and evidence-backed. Counts are technical evidence, not field validation or acceptance.',[['1.3.11+28','Final application version'],['135','Reproduced automated tests'],['0','Final participant/SUS results']],[sources.repo,sources.test]);
split(3,'The app is a local-first Flutter assessment client','Core architecture','Screens and app state coordinate coded profiles, image/video assessment, REBA/ISO calculation, recommendations, history and CSV export.','Network boundary','Core assessment needs no remote assessment database or API. Firebase telemetry is optional and default-off.',[sources.arch,sources.sec]);
timeline(4,'Controlled workflow: collection to evidence',[['COLLECT','Coded profile\nActivity + method\nFour images / video'],['ASSESS','Eligibility + pose\nREBA / ISO rules\nAdvisory models'],['RETAIN / SHARE','Local history\nCSV export\nResearcher policy boundary']],[sources.arch,sources.data,sources.ai]);
evidence(5,'Repository history is the delivery authority','The clean snapshot is supplementary; ownership transfer must preserve history and access controls.',[['Asset','Authority','Human gate'],['Full-history repository','Authoritative','GitHub Owner/Admin transfer'],['Clean source archive','Supplementary snapshot','Verify tree/hash'],['Store/config/signing','External systems','Secure owner transfer'],['Handover package','Reference evidence','Drive audit and readback']],[sources.repo]);
timeline(6,'Local persistence ends at the share boundary',[['STORE','SharedPreferences JSON\nApp-documents media'],['EXPORT','CSV written locally\nOS share sheet'],['GOVERN','Approved destination\nRetention policy\nDeletion unproven']],[sources.data,sources.export,sources.sec]);
metrics(7,'Traceable algorithms; bounded validation','Deterministic REBA/ISO rules and model roles have paths/hashes. Governed data and metrics remain pending.',[['55','Algorithm/reference cases'],['10','Model / algorithm roles'],['2','XGBoost gaps: dataset + raw metrics']],[sources.ai,sources.test]);
evidence(8,'Privacy controls are technical and procedural','The offline inspection is disclosed; it is not a sealed security report or compliance certification.',[['Boundary','Current evidence','Required closure'],['Telemetry','Default-off build define','Approval + console policy'],['Local records/media','No File.delete path','Retention and deletion evidence'],['CSV share','User-triggered OS share','Approved destination + recipient controls'],['Credentials/signing','Categories only; no values','Secure transfer, rotation and revocation'],['Incidents','Draft actions','Approved contacts, SLA and exercise']],[sources.sec,sources.data]);
metrics(9,'Automated evidence; field gates open','Host/unit/widget results do not replace device, participant, SUS, performance or acceptance evidence.',[['135','Automated tests passed'],['7','Historical UAT records'],['0','Final UAT / SUS / acceptance']],[sources.test,sources.uat]);
timeline(10,'Three owner gates to production release',[['SIGN','Android upload key\nApple distribution assets'],['VALIDATE','Physical devices\nPerformance + UAT\nResearch review'],['PUBLISH','Store roles\nRelease approval\nVersion/tag evidence']],[sources.repo,sources.test]);
split(11,'Operations require custody and recovery rules','Current behavior','Records, drafts and media are local. Exports can leave through OS share. No governed backup/restore or file deletion is evidenced.','Required procedure','Approve custody, restore testing, retention, deletion evidence, secure transfer and incident contacts before field use.',[sources.data,sources.export,sources.sec]);
evidence(12,'Troubleshooting starts with bounded evidence','Escalate with coded identifiers, version, device, timestamp, exact steps and non-identifying logs.',[['Symptom','First response','Do not do'],['Camera/gallery denied','Check OS permission and retry','Do not grant unrelated access'],['Pose/person count','One visible person; improve frame/light','Do not treat failure as low risk'],['Export/share failure','Check storage/destination app','Do not use unapproved channels'],['Missing local data','Stop, preserve facts, notify owner','Do not reconstruct participant facts'],['Build/signing failure','Check toolchain and owner assets','Do not label technical build production']],[sources.data,sources.test,sources.sec]);
timeline(13,'Ownership transfer is an evidence sequence',[['TRANSFER','GitHub / Firebase\nApple / Google Play\nSigning categories'],['VERIFY','Named roles\nReadback / audit trail\nRotation decision'],['ACKNOWLEDGE','KT minutes\nOpen actions\nAuthorized signatures']],[sources.repo,sources.sec,sources.minutes]);
metrics(14,'Close with evidence, not assumptions','Attach closure evidence and obtain authorized decisions and signatures. Until then, the package is not finally accepted.',[['5','Owner / researcher action groups'],['3','KT acknowledgement roles'],['1','Next step: evidence review meeting']],[sources.sec,sources.test,sources.minutes]);
await fs.mkdir(path.dirname(OUT),{recursive:true});await fs.mkdir(RENDER,{recursive:true});for(const [i,s] of P.slides.items.entries()){const stem=`slide-${String(i+1).padStart(2,'0')}`;const png=await P.export({slide:s,format:'png',scale:2});await fs.writeFile(path.join(RENDER,`${stem}.png`),new Uint8Array(await png.arrayBuffer()));const layout=await s.export({format:'layout'});await fs.writeFile(path.join(RENDER,`${stem}.layout.json`),await layout.text())}const montage=await P.export({format:'webp',montage:true,scale:1});await fs.writeFile(path.join(RENDER,'deck-montage.webp'),new Uint8Array(await montage.arrayBuffer()));const inspection=await P.inspect({kind:'slide,textbox,shape,notes',maxChars:50000});await fs.writeFile(path.join(RENDER,'deck-inspection.ndjson'),inspection.ndjson);const pptx=await PresentationFile.exportPptx(P);await pptx.save(OUT);console.log(JSON.stringify({status:'built',slides:P.slides.items.length,output:OUT}));
