#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";
import JSZip from "jszip";

const STAGING="/private/tmp/fsookta-final-handover", VERSION="1.3.11+28", COMMIT="bf8867a2083357cb9d60915bf6c2233801f923d8";
export const printFitToHeight="0", printTitleRows="$1:$4", printTitlesInsertionAnchor="calcPr", susBlankRows=10, workbookFont="Thonburi";
export const allowedStatuses=["PASS","FAIL","BLOCKED","Historical Observation","Pending Owner Action","Pending Researcher Evidence","N/A with Rationale","Technical Build Only","Complete - Pending Signature"];
const allowed=new Set(allowedStatuses);
export function assertAllowedStatus(v){if(!allowed.has(v))throw new Error(`Unsupported status: ${v}`);return v;}
export const auditSheetNames=["Control Summary","Timeline Milestones","Requirement Traceability","Version History","Feedback Modifications","Before After Evidence","Decisions Tradeoffs","Challenges Solutions","Effort Summary","Evidence Index","Human Actions"];
export const masterTestSheetNames=["Control Summary","Test Plan","Requirement Test Trace","Functional Cases","Invalid Missing Inputs","Network Error Applicability","Algorithm Reference","Threshold Boundaries","Automated Suite","Integration Regression","Device Compatibility","Performance","Bugs Corrections Retest","Evidence Index","Limitations","Human Actions"];
export const uatSheetNames=["Control Summary","Protocol","Scenarios Tasks","Participant Form","Farmer Profile","Device Build Matrix","Observations Results","Issues Retest","Historical Evidence","Version Comparison","SUS Response Form","Evidence Index","Acceptance Signoff","Limitations Human Actions"];
const C={navy:"#17365D",blue:"#D9EAF7",pale:"#F4F7FA",white:"#FFFFFF",ink:"#1F2937",gray:"#6B7280",line:"#CBD5E1",amber:"#FFF2CC",green:"#E2F0D9",red:"#FCE8E6"};
export function auditRows(f){return f.git_history.map(r=>[r.commit,r.date,r.subject,r.changed_paths,r.refs||"", "Implementation fact from Git", COMMIT]);}
export function masterCaseRows(f){return f.final_test_cases.map(r=>[r.case_id,r.requirement_id,r.category,r.precondition,r.input,r.expected,r.actual,assertAllowedStatus(r.status),r.baseline,r.tester_category,r.timestamp,r.method,r.evidence_sha256,r.evidence_path,r.limitations]);}
export function historicalUatRows(f){return f.historical_uat.map(r=>[r.evidence_id,r.date,r.version,r.device,r.platform,r.method,r.result,r.bypass_status,r.limitations,r.evidence_layer,r.evidence_path,r.sha256]);}
export function susScoreFormula(row){return `=IF(COUNTA(C${row}:L${row})<>10,"",((C${row}-1)+(5-D${row})+(E${row}-1)+(5-F${row})+(G${row}-1)+(5-H${row})+(I${row}-1)+(5-J${row})+(K${row}-1)+(5-L${row}))*2.5)`;}
export function formulaContracts(){return [
  {workbook:"audit",range:"Control Summary!B5",expectedFormula:"=COUNTA('Version History'!A5:A500)"},{workbook:"audit",range:"Control Summary!B6",expectedFormula:"=COUNTA('Requirement Traceability'!A5:A300)"},{workbook:"audit",range:"Control Summary!B7",expectedFormula:"=COUNTIF('Human Actions'!D5:D100,\"Pending Owner Action\")+COUNTIF('Human Actions'!D5:D100,\"Pending Researcher Evidence\")"},
  {workbook:"master",range:"Control Summary!B5",expectedFormula:"=COUNTIF('Automated Suite'!H5:H300,\"PASS\")"},{workbook:"master",range:"Control Summary!B6",expectedFormula:"=COUNTA('Algorithm Reference'!A5:A300)"},{workbook:"master",range:"Control Summary!B7",expectedFormula:"=COUNTIF('Device Compatibility'!H5:H100,\"Pending Owner Action\")"},
  {workbook:"uat",range:"Control Summary!B5",expectedFormula:"=COUNTA('Historical Evidence'!A5:A100)"},{workbook:"uat",range:"Control Summary!B6",expectedFormula:"=COUNTIF('Observations Results'!H5:H100,\"PASS\")"},{workbook:"uat",range:"Control Summary!B7",expectedFormula:"=COUNT('SUS Response Form'!M6:M105)"},{workbook:"uat",range:"Control Summary!B8",expectedFormula:"=COUNTIF('Limitations Human Actions'!D5:D100,\"Pending Owner Action\")+COUNTIF('Limitations Human Actions'!D5:D100,\"Pending Researcher Evidence\")"}
];}
function col(n){let s="";while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function title(sh,name,subtitle,last){sh.showGridLines=false;sh.mergeCells(`A1:${last}1`);sh.getRange("A1").values=[[name]];sh.getRange(`A1:${last}1`).format={fill:C.navy,font:{name:workbookFont,size:18,bold:true,color:C.white},verticalAlignment:"center"};sh.getRange(`A1:${last}1`).format.rowHeight=30;sh.mergeCells(`A2:${last}2`);sh.getRange("A2").values=[[`${subtitle} | ${VERSION} | Git ${COMMIT}`]];sh.getRange(`A2:${last}2`).format={fill:C.pale,font:{name:workbookFont,size:10,color:C.gray},wrapText:true};sh.getRange(`A2:${last}2`).format.rowHeight=32;}
function matrix(sh,name,subtitle,headers,rows,widths){const last=col(headers.length);title(sh,name,subtitle,last);sh.getRange(`A4:${last}4`).values=[headers];sh.getRange(`A4:${last}4`).format={fill:C.blue,font:{name:workbookFont,size:10,bold:true,color:C.ink},wrapText:true,verticalAlignment:"center",borders:{preset:"all",style:"thin",color:C.line}};sh.getRange(`A4:${last}4`).format.rowHeight=42;if(rows.length){sh.getRange(`A5:${last}${rows.length+4}`).values=rows;sh.getRange(`A5:${last}${rows.length+4}`).format={font:{name:workbookFont,size:9,color:C.ink},wrapText:true,verticalAlignment:"top",borders:{insideHorizontal:{style:"thin",color:C.line},bottom:{style:"thin",color:C.line}}};sh.getRange(`A5:${last}${rows.length+4}`).format.rowHeight=48;}widths.forEach((w,i)=>sh.getRangeByIndexes(0,i,Math.max(rows.length+4,5),1).format.columnWidth=w);sh.freezePanes.freezeRows(4);}
const actionRows=f=>f.final_hardware_actions.map(r=>[r.action_id,r.action,r.owner,assertAllowedStatus(r.status),r.closure_evidence]);
const evidenceRows=f=>Object.entries(f.final_commands).map(([k,v])=>[k,v.command,v.status,v.timestamp,v.path,v.sha256,v.limitation||"Host technical evidence boundary"]);
async function auditBook(f){const wb=Workbook.create(),s=Object.fromEntries(auditSheetNames.map(n=>[n,wb.worksheets.add(n)]));
 matrix(s["Version History"],"Complete Git Version History","137 commit-derived rows",["Commit","Date","Subject","Changed paths","Refs/tags/branches","Evidence class","Frozen baseline"],auditRows(f),[38,25,55,75,35,28,38]);
 matrix(s["Timeline Milestones"],"Development Timeline and Milestones","Dates and subjects derived from Git; no invented contract milestones",["Milestone","Date","Commit","Evidence","Classification","Approval status"],f.git_history.filter((r,i)=>i%12===0||/release|merge|uat|test|model|export/i.test(r.subject)).map((r,i)=>[`M-${String(i+1).padStart(3,"0")}`,r.date,r.commit,r.subject,"Implementation fact","Human acceptance not inferred"]),[18,25,38,65,30,35]);
 matrix(s["Requirement Traceability"],"Requirement Traceability Matrix","Governing rows mapped without silent promotion",["Requirement ID","Section","Deliverable","Status","Mapped evidence","Version boundary"],f.requirements_traceability.map(r=>[r.requirement_id,r.section,r.deliverable,r.status,r.evidence,r.baseline_boundary]),[18,18,65,30,65,55]);
 matrix(s["Feedback Modifications"],"Feedback and Modification Register","Git-supported modifications; original feedback author/date requires owner evidence",["ID","Observed change","Source","Feedback author/date","Implementation evidence","Status"],f.git_history.filter(r=>/fix|refactor|improve|align|update/i.test(r.subject)).slice(0,80).map((r,i)=>[`FM-${i+1}`,r.subject,r.commit,"Pending Owner Action",r.changed_paths,"Implementation fact; feedback provenance pending"]),[18,55,38,35,75,45]);
 matrix(s["Before After Evidence"],"Before / After Evidence Index","Repository evidence only; unavailable Figma/prototype claims are not reconstructed",["ID","Change","Before evidence","After evidence","Version/date","Status"],f.git_history.filter(r=>/fix|improve|align|update/i.test(r.subject)).slice(0,40).map((r,i)=>[`BA-${i+1}`,r.subject,"Prior parent commit / historical evidence","Commit and changed paths",r.date,"Implementation fact; visual approval pending"]),[18,60,50,50,26,40]);
 matrix(s["Decisions Tradeoffs"],"Decision and Technical Trade-off Log","Evidence-grounded decisions from commit subjects and package rulings",["ID","Decision","Trade-off","Evidence","Authority","Status"],[["D-01","Full-history repository authoritative; clean snapshot supplementary","Auditability over minimality","Task 3 handover ruling","Technical package","Complete - Pending Signature"],["D-02","Offline assessment with optional default-off telemetry","Local privacy/function vs optional observability","03_API_Applicability_Statement.docx","Source behavior","Complete - Pending Signature"],["D-03","Automated evidence does not substitute for UAT","Conservative acceptance boundary","Task 6 governing brief","Research/owner","Pending Researcher Evidence"]],[18,58,55,55,28,35]);
 matrix(s["Challenges Solutions"],"Challenges and Solutions","Verified technical challenges; acceptance consequences remain visible",["ID","Challenge","Implemented response","Evidence","Residual risk","Status"],[["C-01","File-provider metadata can affect iOS signing","Clean-path/no-codesign technical evidence; no store-readiness claim","Task 2 logs and historical UAT","Distribution signing unverified","Pending Owner Action"],["C-02","Physical-device automation unstable historically","Ready-to-use manual UAT protocol","Historical UAT evidence","Final device execution pending","Pending Owner Action"],["C-03","Research/model evidence incomplete","Explicit pending researcher/owner actions","Task 5 package","No external/clinical validity","Pending Researcher Evidence"]],[18,55,55,55,55,35]);
 matrix(s["Effort Summary"],"Effort Summary","No labor hours, costs, or contractual effort invented",["Workstream","Evidence-derived proxy","Count","Unit","Limit","Human action"],[["Git development","Commits through authoritative baseline",f.git_history.length,"commits","Not labor hours","Owner supplies approved effort/cost if required"],["Final automation","Completed final raw tests",f.final_test_cases.length,"tests","Not UAT participants or device hours","Researcher runs UAT"],["Historical UAT","Indexed repository records",f.historical_uat.length,"documents","Version-specific only","Researcher interprets"]],[30,55,18,22,52,55]);
 matrix(s["Evidence Index"],"Audit Evidence Index","Hash-bound final logs",["ID","Command","Status","Timestamp","Path","SHA-256","Boundary"],evidenceRows(f),[20,45,28,28,55,38,60]);matrix(s["Human Actions"],"Audit Human Actions","Technical completeness is separate from acceptance",["ID","Action","Owner","Status","Closure evidence"],actionRows(f),[18,80,30,30,60]);
 matrix(s["Control Summary"],"Development Audit Control Summary","Formula-driven coverage and pending controls",["Metric","Value","Acceptance gate"],[["Git commits",null,"Must equal source history"],["Requirements mapped",null,"All governing rows present"],["Pending owner/research actions",null,"Must remain visible"],["Labor hours","N/A with Rationale","Not inferable from Git"],["Overall status","Complete - Pending Signature","Owner/researcher acceptance pending"]],[42,24,75]);s["Control Summary"].getRange("B5").formulas=[["=COUNTA('Version History'!A5:A500)"]];s["Control Summary"].getRange("B6").formulas=[["=COUNTA('Requirement Traceability'!A5:A300)"]];s["Control Summary"].getRange("B7").formulas=[["=COUNTIF('Human Actions'!D5:D100,\"Pending Owner Action\")+COUNTIF('Human Actions'!D5:D100,\"Pending Researcher Evidence\")"]];return wb;}
async function masterBook(f){const wb=Workbook.create(),s=Object.fromEntries(masterTestSheetNames.map(n=>[n,wb.worksheets.add(n)])),all=masterCaseRows(f),alg=all.filter(r=>r[2]==="Algorithm/reference"),fun=all.filter(r=>r[2]!=="Algorithm/reference");
 matrix(s["Automated Suite"],"Final Automated Suite","Every PASS bound to final raw log and SHA-256",["Case ID","Requirement ID","Category","Precondition","Input/assertion","Expected","Actual","Status","Baseline","Tester category","UTC timestamp","Command/method","Evidence SHA-256","Evidence path","Limitations"],all,[18,18,28,45,68,48,58,18,24,28,28,45,38,55,65]);
 matrix(s["Functional Cases"],"Functional and Regression Cases","Host evidence only",["Case ID","Requirement ID","Category","Precondition","Input/assertion","Expected","Actual","Status","Baseline","Tester category","UTC timestamp","Method","Evidence SHA-256","Evidence path","Limitations"],fun,[18,18,28,45,68,48,58,18,24,28,28,45,38,55,65]);
 matrix(s["Algorithm Reference"],"Algorithm and Reference Cases","Deterministic/source assertions; no research validation inference",["Case ID","Requirement ID","Category","Precondition","Input/assertion","Expected","Actual","Status","Baseline","Tester category","UTC timestamp","Method","Evidence SHA-256","Evidence path","Limitations"],alg,[18,18,28,45,68,48,58,18,24,28,28,45,38,55,65]);
 matrix(s["Threshold Boundaries"],"Threshold Boundary Inventory","Cases selected by source-controlled assertion names",["Case ID","Assertion","Expected","Actual","Status","Baseline","Evidence","Boundary limitation"],alg.filter(r=>/low|medium|high|limit|threshold|floor|boundary|score|risk/i.test(r[4])).map(r=>[r[0],r[4],r[5],r[6],r[7],r[8],r[13],r[14]]),[18,70,50,58,18,24,55,60]);
 matrix(s["Test Plan"],"Master Test Plan","Final, historical, blocked, and N/A layers remain distinct",["Layer","Objective","Method","Allowed claim","Status","Owner/action"],[["Final static","Source quality","flutter analyze","Static analysis only","PASS","Automated runner"],["Final automated","Deterministic/functional regression","flutter test","Host assertion only","PASS","Automated runner"],["Final build","Compilation/package","release build commands","Technical build only","Technical Build Only","Owner verifies signing/store"],["Physical device","Permissions/audio/share/offline","Manual production path","Only observed device behavior","Pending Owner Action","Owner executes protocol"],["Participant UAT/SUS","Usability/acceptance","Approved research protocol","Only coded consented observations","Pending Researcher Evidence","Researcher executes/interprets"]],[26,55,50,58,30,55]);
 matrix(s["Requirement Test Trace"],"Requirement-to-Test Traceability","Test linkage does not upgrade unmet human evidence",["Requirement ID","Deliverable","Mapped automated cases","Automated status","Device/UAT status","Evidence boundary"],f.requirements_traceability.map(r=>[r.requirement_id,r.deliverable,all.filter(x=>x[1]===r.requirement_id).map(x=>x[0]).join("; ")||"None",all.some(x=>x[1]===r.requirement_id)?"PASS":"N/A with Rationale",r.status,r.baseline_boundary]),[18,65,45,28,30,60]);
 const invalid=all.filter(r=>/invalid|missing|required|empty|unavailable|error|fallback|reject|block|zero|unsupported/i.test(r[4]));matrix(s["Invalid Missing Inputs"],"Invalid, Missing, and Unsupported Inputs","Evidence-backed negative cases",["Case","Assertion","Expected","Actual","Status","Evidence","Limitation"],invalid.map(r=>[r[0],r[4],r[5],r[6],r[7],r[13],r[14]]),[18,72,48,55,18,55,60]);
 matrix(s["Network Error Applicability"],"Network and Error Applicability","Offline assessment separated from optional telemetry and device proof",["Area","Applicability","Final evidence","Status","Rationale/action"],[["Assessment backend/API","Not applicable","03_API_Applicability_Statement.docx","N/A with Rationale","No backend assessment API in source"],["Optional Firebase telemetry","Applicable only when enabled","Source tests / Task 5 documentation","PASS","Does not prove dashboard custody or retention"],["Offline physical inference","Applicable","No final device observation","Pending Owner Action","Disable network and execute production path"],["Share/export destination","Applicable","Host export tests only","Pending Owner Action","Validate native share sheet and receiving app"]],[32,35,55,30,70]);
 matrix(s["Integration Regression"],"Integration and Regression Classification","Automated runner scope retained",["Case","Source path","Class","Status","Evidence","Limitation"],all.filter(r=>/integration|screen|flow|state|service/i.test(r[14]+r[4])).map(r=>[r[0],r[14],r[2],r[7],r[13],"Host runner; physical integration not inferred"]),[18,55,32,18,55,60]);
 const dev=f.final_hardware_actions.filter(r=>/device|camera|gallery|tts|share|offline|tablet/.test(r.action_key));matrix(s["Device Compatibility"],"Device Compatibility","No unsupported final compatibility PASS",["Action ID","Platform/function","Precondition","Expected","Actual","Method","Evidence","Status","Baseline","Owner"],dev.map(r=>[r.action_id,r.action_key,"Final signed/approved build on in-scope physical device","Complete flow without crash/data loss; record exact observation","Not executed on final baseline","Manual protocol","Pending raw log/screenshots/hash",r.status,VERSION,r.owner]),[18,25,50,55,38,34,55,30,24,30]);
 matrix(s["Performance"],"Performance Verification","Quantitative metrics require approved thresholds and raw measurements",["Metric","Unit","Acceptance threshold","Method","Final value","Status","Owner action"],[["Cold start","ms","Pending Owner Action","Instrumented release build",null,"Pending Owner Action","Approve threshold and collect >=3 runs/device"],["Image inference","ms/image","Pending Owner Action","Production-path physical device",null,"Pending Owner Action","Collect model/device/raw timing"],["CSV export","ms/record count","Pending Owner Action","Known synthetic dataset sizes",null,"Pending Owner Action","Define sizes and collect logs"],["Memory/stability","MB/crash-free session","Pending Owner Action","Profiler and sustained field flow",null,"Pending Owner Action","Approve protocol and collect evidence"]],[30,24,35,50,24,30,65]);
 matrix(s["Bugs Corrections Retest"],"Bugs, Corrections, and Retest Register","Ready-to-use final register; historical issues are not silently closed",["Bug ID","Version","Description","Severity","Evidence","Correction commit/build","Retest method","Retest result","Status","Owner"],[["T6-PENDING-01",VERSION,"Final physical-device/UAT defects not yet collected","TBD","Pending final protocol","Pending","Repeat exact production path","Pending","Pending Owner Action","Owner/researcher"]],[20,24,60,18,55,38,55,30,30,30]);
 matrix(s["Evidence Index"],"Test Evidence Index","Final raw logs with hashes",["ID","Command","Status","Timestamp","Path","SHA-256","Boundary"],evidenceRows(f),[20,45,28,28,55,38,60]);matrix(s["Limitations"],"Verification Limitations","Explicit non-claims",["ID","Limitation","Impact","Status","Required action"],[["L-01","Build success is not functional/device/UAT proof","Compatibility and permissions unverified","Pending Owner Action","Run device protocol"],["L-02","Automated TTS mocks/logs do not prove audible clarity","Human listening required","Pending Researcher Evidence","Listen and record coded result"],["L-03","No approved quantitative performance criteria","No performance PASS","Pending Owner Action","Approve thresholds and collect raw metrics"],["L-04","No external/clinical validation evidence","No diagnostic/generalization claim","Pending Researcher Evidence","Define and conduct governed validation if required"]],[18,65,60,30,65]);matrix(s["Human Actions"],"Test and Verification Human Actions","Closure requires exact evidence",["ID","Action","Owner","Status","Closure evidence"],actionRows(f),[18,80,30,30,60]);
 matrix(s["Control Summary"],"Master Test and Verification Summary","Formula-driven evidence counts",["Metric","Value","Gate"],[["Final automated PASS",null,"Must equal final raw log"],["Algorithm/reference cases",null,"Each cites final evidence"],["Pending device actions",null,"Cannot be promoted"],["Final build status","Technical Build Only","Signing/store unverified"],["Overall status","Complete - Pending Signature","Human evidence/acceptance pending"]],[42,24,78]);s["Control Summary"].getRange("B5").formulas=[["=COUNTIF('Automated Suite'!H5:H300,\"PASS\")"]];s["Control Summary"].getRange("B6").formulas=[["=COUNTA('Algorithm Reference'!A5:A300)"]];s["Control Summary"].getRange("B7").formulas=[["=COUNTIF('Device Compatibility'!H5:H100,\"Pending Owner Action\")"]];return wb;}
async function uatBook(f){const wb=Workbook.create(),s=Object.fromEntries(uatSheetNames.map(n=>[n,wb.worksheets.add(n)]));
 matrix(s["Protocol"],"Final UAT and Field-Test Protocol","Ready to use; consent/research approval required before data collection",["Step","Instruction","Evidence to capture","Privacy/control","Owner","Status"],[[1,"Confirm approved protocol, consent, device scope and final build","Approval IDs; no secrets","Participant code only","Researcher","Pending Researcher Evidence"],[2,"Record device/OS/build and production-path or harness status","Device metadata and timestamp","No device owner identity","UAT lead","Pending Owner Action"],[3,"Execute each scenario without bypass unless explicitly recorded","Observation, screenshot/log hash","No raw face/photo in package","UAT lead","Pending Researcher Evidence"],[4,"Capture issue, correction build/commit and exact retest","Bug/retest evidence","De-identify notes","Technical reviewer","Pending Owner Action"],[5,"Collect SUS 1-5 responses and compute only when complete","Coded form","Consent + coded ID","Researcher","Pending Researcher Evidence"],[6,"Review acceptance criteria and sign decision","Signed acceptance record","Authorized roles only","Owner/researcher","Complete - Pending Signature"]],[18,75,60,55,30,30]);
 const scenarios=[["UAT-01","Onboarding and language","Fresh install","Select Thai/English; complete coded profile","Correct route, readable content, persisted coded profile"],["UAT-02","Farmer management","Setup complete","Add/edit/select/delete synthetic/coded farmer","Correct active profile and no unintended loss"],["UAT-03","Camera acquisition","Physical device","Grant/deny permission; capture valid image","Clear permission/failure handling; selected image visible"],["UAT-04","Gallery acquisition","Physical device","Grant/deny permission; select valid/invalid image","Clear failure; no score for invalid/no eligible person"],["UAT-05","Assessment and recommendation","Eligible images/input","Complete REBA/ISO path","Deterministic result and cited recommendation displayed"],["UAT-06","History and draft","Partial/completed assessment","Save/restore/clear draft and reopen history","No phantom/duplicate loss; correct version data"],["UAT-07","Export/share","Completed record","Export and open native share sheet","Correct file/schema and receiver can access"],["UAT-08","TTS","Thai/English result","Listen on speaker/headphones","Understandable, correct language, no truncation"],["UAT-09","Offline inference","Network disabled","Complete production assessment","No backend dependency; explicit optional telemetry behavior"],["UAT-10","Error recovery","Invalid/missing/unsupported input","Trigger each error","No misleading numeric result; actionable message"]];matrix(s["Scenarios Tasks"],"UAT Scenarios and Success Criteria","No result prefilled",["Scenario ID","Area","Precondition","Task","Success criterion","Final status","Evidence ID"],scenarios.map(r=>[...r,"Pending Researcher Evidence",""]),[18,30,45,65,70,30,28]);
 matrix(s["Participant Form"],"Participant-Coded Observation Form","Blank controlled form - do not enter direct identity",["Participant code","Consent/approval ID","Session UTC/local date","Scenario ID","Task outcome","Observation","Assistance required","Issue ID","Evidence ID","Researcher review"],[["","","","","","","","","","Pending Researcher Evidence"]],[25,30,28,18,28,65,25,20,24,30]);
 matrix(s["Farmer Profile"],"Privacy-Safe Farmer Profile Context","Optional research context; coded and approved fields only",["Participant code","Agricultural activity","Experience band","Age band if approved","Region band if approved","Accessibility notes","Consent scope","Status"],[["","","","","","","","Pending Researcher Evidence"]],[25,38,28,28,32,50,50,30]);
 matrix(s["Device Build Matrix"],"Final Device, OS, and Build Matrix","No compatibility PASS without raw observation",["Record ID","Participant code","Platform","Device model","OS","App version","Build path/class","Production path?","Bypass/harness","Timestamp","Result","Evidence/hash"],[["DEV-001","","Android","Pending","Pending",VERSION,"Pending approved build","Pending","None unless recorded","","Pending Owner Action",""],["DEV-002","","iOS/iPhone","Pending","Pending",VERSION,"Pending approved build","Pending","None unless recorded","","Pending Owner Action",""],["DEV-003","","Tablet if in scope","Pending","Pending",VERSION,"Pending approved build","Pending","None unless recorded","","Pending Owner Action",""]],[18,24,24,28,22,24,40,24,30,28,30,50]);
 matrix(s["Observations Results"],"Final-Baseline Observations and Results","Blank until consented human execution",["Observation ID","Participant code","Scenario ID","Precondition/input","Expected","Actual","Method","Status","Baseline","Tester category","Timestamp","Evidence path/hash","Assistance/bypass","Notes"],[["","","","","","","Manual production path","Pending Researcher Evidence",VERSION,"Human participant / researcher","","","","No final observations supplied"]],[20,24,18,55,50,55,40,30,24,35,28,55,32,55]);
 matrix(s["Issues Retest"],"UAT Issues, Corrective Actions, and Retest", "Do not close without exact retest evidence",["Issue ID","Observation ID","Severity","Description","Evidence","Corrective action","Commit/build","Retest method","Retest result","Status","Owner"],[["","","","","","","","","","Pending Owner Action",""]],[18,20,18,60,50,60,38,55,32,30,30]);
 matrix(s["Historical Evidence"],"Historical Field-Test Evidence","Original version/device/method/bypass retained",["Evidence ID","Date","Version","Device","Platform","Method","Result","Bypass status","Limitations","Evidence layer","Evidence path","SHA-256"],historicalUatRows(f),[18,22,28,40,24,45,28,42,70,24,60,38]);
 matrix(s["Version Comparison"],"Historical versus Final Baseline","No historical result upgrades",["Layer","Version","Evidence available","Can prove final UAT?","Required next action"],[["Historical repository records","1.1.2+10 through pre-final versions",`${f.historical_uat.length} indexed records`,"No","Retain context only"],["Final automated",VERSION,`${f.final_test_cases.length} host tests`,"No","Use for technical regression only"],["Final build",VERSION,"Android/iOS technical build logs","No","Verify signing, install, device flows"],["Final participant UAT",VERSION,"No observations; participant count 0","No","Approved protocol + consent + coded participants"],["Final SUS",VERSION,"No responses or score","No","Collect 10 responses per participant"]],[32,34,55,30,65]);
 const susHeaders=["Participant code","Session/evidence ID","Q1","Q2","Q3","Q4","Q5","Q6","Q7","Q8","Q9","Q10","SUS score","Completeness/status","Researcher interpretation"];
 const susRows=[];for(let i=0;i<susBlankRows;i++)susRows.push(["","",null,null,null,null,null,null,null,null,null,null,null,"Pending Researcher Evidence",""]);matrix(s["SUS Response Form"],"System Usability Scale (SUS) Response Form","Enter integers 1-5 only; score stays blank until all 10 items are present",susHeaders,susRows,[24,26,10,10,10,10,10,10,10,10,10,10,18,30,55]);for(let r=5;r<5+susBlankRows;r++){s["SUS Response Form"].getRange(`M${r}`).formulas=[[susScoreFormula(r)]];s["SUS Response Form"].getRange(`C${r}:L${r}`).dataValidation={rule:{type:"whole",operator:"between",formula1:1,formula2:5}};}
 matrix(s["Evidence Index"],"UAT Evidence Index","Final technical and historical source layers",["Evidence ID","Layer","Version","Path","SHA-256","Result","Boundary"],[...evidenceRows(f).map(r=>[r[0],"Final technical",VERSION,r[4],r[5],r[2],r[6]]),...f.historical_uat.map(r=>[r.evidence_id,"Historical",r.version,r.evidence_path,r.sha256,r.result,r.limitations])],[20,24,28,65,38,28,70]);
 matrix(s["Acceptance Signoff"],"Acceptance and Sign-off","No final acceptance inferred",["Role","Name","Decision","Conditions/outstanding items","Signature","Date","Status"],[["UAT lead","Pending","Pending","Final device protocol and defect/retest evidence","Pending","","Complete - Pending Signature"],["Researcher / ethics owner","Pending","Pending","Consent, participant evidence, SUS interpretation","Pending","","Complete - Pending Signature"],["Product owner / authorized acceptor","Pending","Pending","Review all critical actions and exceptions","Pending","","Complete - Pending Signature"]],[32,28,28,70,28,24,35]);matrix(s["Limitations Human Actions"],"UAT Limitations and Human Actions","Exact closure evidence required",["ID","Action","Owner","Status","Closure evidence"],actionRows(f),[18,80,30,30,60]);
 matrix(s["Control Summary"],"UAT, Field Test, and Usability Summary","Formula-driven, fail-closed final status",["Metric","Value","Gate"],[["Historical evidence records",null,"Version labels retained"],["Final-baseline PASS observations",null,"Must remain 0 until raw human evidence"],["Completed SUS scores",null,"Must remain 0 until ten responses per row"],["Pending owner/research actions",null,"Must remain visible"],["Participant count",0,"No participants supplied"],["Final UAT status","Pending Researcher Evidence","Cannot be inferred from automation/build"]],[45,28,78]);s["Control Summary"].getRange("B5").formulas=[["=COUNTA('Historical Evidence'!A5:A100)"]];s["Control Summary"].getRange("B6").formulas=[["=COUNTIF('Observations Results'!H5:H100,\"PASS\")"]];s["Control Summary"].getRange("B7").formulas=[["=COUNT('SUS Response Form'!M6:M105)"]];s["Control Summary"].getRange("B8").formulas=[["=COUNTIF('Limitations Human Actions'!D5:D100,\"Pending Owner Action\")+COUNTIF('Limitations Human Actions'!D5:D100,\"Pending Researcher Evidence\")"]];return wb;}
async function applyPrint(file,names){const zip=await JSZip.loadAsync(await fs.readFile(file));for(const n of Object.keys(zip.files).filter(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x))){let xml=await zip.file(n).async("string");const prefix=xml.match(/<([A-Za-z0-9_]+:)?worksheet\b/)?.[1]??"";const tag=x=>`${prefix}${x}`;if(new RegExp(`<${tag("sheetPr")}\\b[^>]*\\/>`).test(xml))xml=xml.replace(new RegExp(`<${tag("sheetPr")}\\b([^>]*)\\/>`),`<${tag("sheetPr")}$1><${tag("pageSetUpPr")} fitToPage="1"/></${tag("sheetPr")}>`);else if(new RegExp(`<${tag("sheetPr")}\\b`).test(xml))xml=xml.replace(new RegExp(`</${tag("sheetPr")}>`),`<${tag("pageSetUpPr")} fitToPage="1"/></${tag("sheetPr")}>`);else xml=xml.replace(new RegExp(`(<${tag("worksheet")}\\b[^>]*>)`),`$1<${tag("sheetPr")}><${tag("pageSetUpPr")} fitToPage="1"/></${tag("sheetPr")}>`);for(const local of ["printOptions","pageMargins","pageSetup"])xml=xml.replace(new RegExp(`<${tag(local)}\\b[^>]*\\/>`,"g"),"");xml=xml.replace(`</${tag("worksheet")}>`,`<${tag("printOptions")} horizontalCentered="1"/><${tag("pageMargins")} left="0.18" right="0.18" top="0.3" bottom="0.3" header="0.12" footer="0.12"/><${tag("pageSetup")} paperSize="8" orientation="landscape" fitToWidth="1" fitToHeight="${printFitToHeight}" horizontalDpi="300" verticalDpi="300"/></${tag("worksheet")}>`);zip.file(n,xml);}let workbookXml=await zip.file("xl/workbook.xml").async("string");const definitions=names.map((name,index)=>`<definedName name="_xlnm.Print_Titles" localSheetId="${index}">'${name.replaceAll("&","&amp;")}'!${printTitleRows}</definedName>`).join("");if(/<definedNames>/.test(workbookXml))workbookXml=workbookXml.replace("</definedNames>",`${definitions}</definedNames>`);else if(/<calcPr\b/.test(workbookXml))workbookXml=workbookXml.replace(/<calcPr\b/,`<definedNames>${definitions}</definedNames><calcPr`);else workbookXml=workbookXml.replace("</workbook>",`<definedNames>${definitions}</definedNames></workbook>`);zip.file("xl/workbook.xml",workbookXml);await fs.writeFile(file,await zip.generateAsync({type:"nodebuffer",compression:"DEFLATE",compressionOptions:{level:9}}));}
async function renderBook(wb,stem,names){const dir=path.join(STAGING,"renders","task6",stem);await fs.mkdir(dir,{recursive:true});const paths=[];for(const name of names){const blob=await wb.render({sheetName:name,autoCrop:"all",scale:1,format:"png"});const p=path.join(dir,`${name.replaceAll(/[^A-Za-z0-9]+/g,"_")}.png`);await fs.writeFile(p,new Uint8Array(await blob.arrayBuffer()));paths.push(p);}return paths;}
async function build(){const f=JSON.parse(await fs.readFile(path.join(STAGING,"working","task6","task6_build_input.json"),"utf8"));const books={audit:await auditBook(f),master:await masterBook(f),uat:await uatBook(f)};const meta={audit:["06_Development_Audit_Trail",auditSheetNames],master:["07_Master_Test_and_Verification_Package",masterTestSheetNames],uat:["08_UAT_Field_Test_and_Usability_Package",uatSheetNames]};const renders=[];for(const [key,wb] of Object.entries(books)){renders.push(...await renderBook(wb,meta[key][0],meta[key][1]));const out=path.join(STAGING,"artifacts",`${meta[key][0]}.xlsx`);await(await SpreadsheetFile.exportXlsx(wb)).save(out);await applyPrint(out,meta[key][1]);}const contracts=[];for(const c of formulaContracts()){const [sn,cell]=c.range.split("!");const wb=books[c.workbook],sh=wb.worksheets.getItem(sn);const formula=sh.getRange(cell).formulas[0][0];if(formula!==c.expectedFormula)throw new Error(`formula mismatch ${c.workbook} ${c.range}`);contracts.push(c);}let formulaErrorMatches=0;for(const wb of Object.values(books)){const scan=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:300},maxChars:3000});if(!/matched 0 entries/i.test(scan.ndjson))throw new Error(scan.ndjson);}const summary={status:"passed",sheets:auditSheetNames.length+masterTestSheetNames.length+uatSheetNames.length,audit_sheets:auditSheetNames.length,master_sheets:masterTestSheetNames.length,uat_sheets:uatSheetNames.length,formula_contracts:contracts,formula_error_matches:formulaErrorMatches,renders};await fs.writeFile(path.join(STAGING,"manifests","task6_workbook_build_summary.json"),JSON.stringify(summary,null,2)+"\n");console.log(JSON.stringify(summary,null,2));}
if(import.meta.url===pathToFileURL(process.argv[1]).href)build().catch(e=>{console.error(e);process.exitCode=1;});
