import fs from 'node:fs/promises';
import path from 'node:path';
import { Workbook, SpreadsheetFile } from '@oai/artifact-tool';

const ROOT=process.env.FSOOKTA_HANDOVER_ROOT || '/private/tmp/fsookta-final-handover';
const A=path.join(ROOT,'artifacts');
const payload=JSON.parse(await fs.readFile(path.join(ROOT,'working/task6/task6_corrected_payload.json'),'utf8'));
const font={name:'Arial',size:9,color:'#172033'};
const PASS_HEADERS=['Case ID','Requirement ID','Test name','Category','Precondition / input','Expected','Actual','Status','Baseline / version','Tester category','Timestamp / date','Exact method / command','Raw evidence path','SHA-256','Limitations','Source path'];
function colName(n){let s=''; while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s;}
function matrix(rows){return rows.map(r=>r.map(v=>v===undefined||v===null?'':typeof v==='object'?JSON.stringify(v):v));}
function fresh(){return new Workbook({}, {sheets:[]});}
function table(wb,name,title,subtitle,headers,rows,widths=[]){
 const s=wb.worksheets.add(name), end=colName(headers.length);
 s.showGridLines=false; s.getRange(`A1:${end}1`).merge(); s.getRange('A1').values=[[title]];
 s.getRange(`A2:${end}2`).merge(); s.getRange('A2').values=[[subtitle]]; s.getRange(`A4:${end}4`).values=[headers];
 if(rows.length) s.getRange(`A5:${end}${rows.length+4}`).values=matrix(rows);
 s.getRange(`A1:${end}${Math.max(4,rows.length+4)}`).format={font,verticalAlignment:'top',wrapText:true};
 s.getRange(`A1:${end}1`).format={fill:'#17365D',font:{name:'Arial',size:16,bold:true,color:'#FFFFFF'},rowHeight:28};
 s.getRange(`A2:${end}2`).format={fill:'#D9EAF7',font:{name:'Arial',size:9,italic:true,color:'#17365D'},rowHeight:30};
 s.getRange(`A4:${end}4`).format={fill:'#2F75B5',font:{name:'Arial',size:9,bold:true,color:'#FFFFFF'},rowHeight:30,borders:{preset:'all',style:'thin',color:'#9FBAD0'}};
 if(rows.length) s.getRange(`A5:${end}${rows.length+4}`).format.borders={preset:'inside',style:'thin',color:'#D9E2F3'};
 widths.forEach((w,i)=>s.getRange(`${colName(i+1)}:${colName(i+1)}`).format.columnWidth=w); s.freezePanes.freezeRows(4); return s;
}
function passRow(r){return [r.case_id,r.requirement_id||'',r.name,r.category,r.precondition_input,r.expected,r.actual,r.status,r.baseline,r.tester_category,r.timestamp,r.method,r.raw_path,r.sha256,r.limitations||'',r.source_path||''];}
function nonResultRow(r){return [r.case_id,'',r.name,r.category,'Human/runtime evidence required','Final-version evidence meeting the plan',r.actual,r.status,'','','','','','',r.limitations,''];}
function governedRows(rows){return rows.map(r=>r.status==='PASS'?passRow(r):nonResultRow(r));}
function reqRows(){return payload.requirements.map(r=>[r.requirement_id,r.status,JSON.stringify(r.authoritative_sources),r.human_action,r.rationale,String(r.final_version_claim),JSON.stringify(r.task2_evidence),JSON.stringify(r.task6_evidence)]);}
function humanRows(){return payload.human_gaps.map(x=>[x.action_id,x.action_key,x.action,x.owner,x.status,x.closure_evidence]);}
function historicalRows(){return payload.historical_uat.map(r=>[r.evidence_id,r.date,r.round_revision,r.version,r.device,r.runner_harness,r.build_workaround,r.assessment_bypass,r.blocker,r.observation,r.evidence_path,r.sha256,r.evidence_layer]);}
function defectRows(){return payload.defects.map(r=>[r.defect_id,r.version,r.description,r.before_commit,r.after_commit,r.source_path,r.before_git_object.changed_paths,r.after_git_object.changed_paths,r.fix,r.retest,r.evidence_path,r.sha256,r.status]);}
async function save(wb,name){const blob=await SpreadsheetFile.exportXlsx(wb); await blob.save(path.join(A,name));}

async function audit(){
 const wb=fresh();
 table(wb,'Control Summary','Development Audit Trail - Canonical Evidence Model',payload.claim_boundary,['Metric','Value','Control'],[['Requirements',155,'Source records preserved'],['Pending Owner Action',137,'Source status'],['Exception Approval Required',12,'Source status'],['Pending Researcher Evidence',6,'Source status'],['Historical defects',3,'Exact git/evidence joins'],['Before/after rows',3,'Exact commits/paths/hashes']],[34,20,75]);
 table(wb,'Timeline Milestones','Canonical Timeline and Milestones','Historical records are not promoted to final baseline',['Evidence ID','Date','Round / revision','Version','Observation','Evidence path','SHA-256'],payload.historical_uat.map(r=>[r.evidence_id,r.date,r.round_revision,r.version,r.observation,r.evidence_path,r.sha256]),[18,18,18,18,70,52,68]);
 table(wb,'Requirement Traceability','Requirement Traceability - Source Status Preserved','155 governing records; terminal counts 137 / 12 / 6',['Requirement ID','Source status','Authoritative sources','Human action','Rationale','Final claim','Task 2 layer','Task 6 layer'],reqRows(),[14,26,65,60,60,14,60,60]);
 table(wb,'Version History','Repository Version History','Source-controlled git history; baseline commit remains authoritative',['Commit','Date','Author','Subject'],payload.git_history.map(x=>[x.commit||x.sha||x.hash,x.date||x.timestamp,x.author,x.subject||x.message]),[45,24,28,90]);
 table(wb,'Feedback Modifications','Feedback and Modifications','Only source-grounded historical corrections are asserted',['Defect ID','Description','Fix','Retest','Version','Evidence path','SHA-256'],payload.defects.map(r=>[r.defect_id,r.description,r.fix,r.retest,r.version,r.evidence_path,r.sha256]),[18,55,52,60,18,52,68]);
 table(wb,'Before After Evidence','Before / After Evidence','Resolvable git commits, ancestry order, changed paths, evidence paths and hashes',['Change ID','Before commit','After commit','Source path','Before','After','Before changed paths','After changed paths','Evidence path','SHA-256'],payload.before_after.map(r=>[r.change_id,r.before_commit,r.after_commit,r.source_path,r.before,r.after,r.before_changed_paths,r.after_changed_paths,r.evidence_path,r.sha256]),[18,42,42,48,55,55,85,85,52,68]);
 table(wb,'Decisions Tradeoffs','Decisions and Tradeoffs','Evidence boundaries are explicit',['Decision','Rationale','Boundary'],[['Canonical 135-test reporter model','Counter +N completes preceding display','Terminal summary excluded'],['Historical evidence separation','Prevents unsupported final claims',payload.claim_boundary],['Manual visual decision','Builder cannot self-assert inspection','External hash-bound decision required']],[50,75,75]);
 table(wb,'Challenges Solutions','Challenges and Solutions','Resolved controls and remaining human boundaries',['Challenge','Solution','Status'],[['Expanded reporter attribution','Stateful parser plus mutation tests','Resolved'],['Dataless workspace','Canonical source files materialized and committed','Resolved'],['Physical/UAT evidence','Controlled forms and explicit human actions','Pending human evidence']],[60,85,36]);
 table(wb,'Effort Summary','Effort Summary','Counts describe generated evidence, not participant effort',['Area','Count','Boundary'],[['Automated tests',135,'Host/unit/widget'],['Static analysis',1,'Automated'],['Historical UAT records',7,'Historical only'],['Human actions',payload.human_gaps.length,'Not automated']],[38,18,75]);
 table(wb,'Evidence Index','Audit Evidence Index','Source-controlled evidence paths and SHA-256',['ID','Type','Path','SHA-256','Status'],[...payload.historical_uat.map(r=>[r.evidence_id,'Historical UAT',r.evidence_path,r.sha256,r.evidence_layer]),...payload.defects.map(r=>[r.defect_id,'Historical defect/retest',r.evidence_path,r.sha256,r.status])],[20,32,60,68,48]);
 table(wb,'Human Actions','Final Human Actions','Automation does not close these actions',['Action ID','Key','Action','Owner','Status','Closure evidence'],humanRows(),[18,22,80,34,36,65]);
 await save(wb,'06_Development_Audit_Trail.xlsx');
}

async function master(){
 const wb=fresh(), auto=payload.result_rows.filter(r=>r.case_id.startsWith('AUTO-')), staticAndPlans=payload.result_rows.filter(r=>!r.case_id.startsWith('AUTO-'));
 const alg=auto.filter(r=>r.category==='Algorithm / reference'), boundary=auto.filter(r=>r.category==='Invalid / boundary'), functional=auto.filter(r=>r.category==='Functional / regression');
 const cats=Object.fromEntries(['Algorithm / reference','Functional / regression','Data / persistence','UI / regression','Invalid / boundary'].map(c=>[c,auto.filter(r=>r.category===c).length]));
 table(wb,'Control Summary','Master Test and Verification Package - Canonical',payload.claim_boundary,['Metric','Value','Control'],[['Exact automated cases',135,'Canonical stateful parser'],...Object.entries(cats),['PASS evidence rows',136,'Full governed schema'],['Firebase runtime','Not Executed','No generic PASS'],['Physical-device acceptance','Not Executed','Human action']],[38,24,75]);
 table(wb,'Test Plan','Final Test Plan','PASS and non-result statuses use governed schemas',PASS_HEADERS,governedRows(staticAndPlans),[18,18,55,26,60,55,55,34,18,30,24,60,50,68,60,50]);
 table(wb,'Requirement Test Trace','Requirement/Test Evidence Boundary','Automated results do not overwrite governing terminal statuses',['Requirement ID','Source status','Human action','Rationale','Task 2 layer','Task 6 layer'],payload.requirements.map(r=>[r.requirement_id,r.status,r.human_action,r.rationale,JSON.stringify(r.task2_evidence),JSON.stringify(r.task6_evidence)]),[14,26,65,65,60,60]);
 table(wb,'Functional Cases','Functional / Regression Cases',`${functional.length} exact normalized joins from canonical test results`,PASS_HEADERS,governedRows(functional),[18,18,60,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Invalid Missing Inputs','Invalid / Missing Input Cases',`${boundary.length} exact normalized joins from canonical test results`,PASS_HEADERS,governedRows(boundary),[18,18,60,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Network Error Applicability','Network / Firebase Applicability','No generic Firebase PASS; runtime delivery remains non-result',PASS_HEADERS,governedRows(payload.result_rows.filter(r=>r.case_id==='FIREBASE-PLAN-001')),[22,18,55,26,55,55,55,40,18,30,24,60,50,68,60,50]);
 table(wb,'Algorithm Reference','Algorithm / Reference Cases',`${alg.length} exact canonical cases; no stale 64-case claim`,PASS_HEADERS,governedRows(alg),[18,18,70,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Threshold Boundaries','Threshold / Boundary Cases',`${boundary.length} exact canonical cases joined by Case ID`,PASS_HEADERS,governedRows(boundary),[18,18,70,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Automated Suite','Final Automated Suite - Exact 135 Completed Tests','+N completes the preceding displayed test; +135 terminal summary is not a test',PASS_HEADERS,governedRows(auto),[18,18,70,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Integration Regression','Integration / Regression Join','All 135 canonical cases retain the same case ID and governed evidence schema',PASS_HEADERS,governedRows(auto),[18,18,70,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Device Compatibility','Device Compatibility Plan','No final physical-device PASS is claimed',['Case ID','Activity','Status','Owner','Required evidence'],payload.human_gaps.filter(x=>['android_device','iphone_device','tablet_device','camera','gallery'].includes(x.action_key)).map(x=>[x.action_id,x.action,x.status,x.owner,x.closure_evidence]),[20,80,38,34,65]);
 table(wb,'Performance','Performance Plan','No performance PASS or threshold is invented',['Case ID','Activity','Status','Owner','Required evidence'],payload.human_gaps.filter(x=>x.action_key==='performance').map(x=>[x.action_id,x.action,x.status,x.owner,x.closure_evidence]),[20,85,38,34,70]);
 table(wb,'Bugs Corrections Retest','Historical Bugs / Corrections / Retest','Exact historical git objects, ancestry, changed paths and evidence joins; not final device evidence',['Defect ID','Version','Description','Before commit','After commit','Source path','Before changed paths','After changed paths','Fix','Retest','Evidence path','SHA-256','Status'],defectRows(),[18,18,55,42,42,50,85,85,50,60,52,68,48]);
 table(wb,'Evidence Index','Hash-bound PASS Evidence Index','Every PASS has the complete governed schema',PASS_HEADERS,governedRows(payload.result_rows.filter(r=>r.status==='PASS')),[18,18,60,26,60,55,55,12,18,30,24,60,50,68,60,50]);
 table(wb,'Limitations','Test Limitations','Claims remain bounded',['Area','Limitation','Required closure'],[['Automated suite','Host/unit/widget only','Physical-device and human evidence'],['Firebase','No final runtime delivery result','Runtime logs with version/date/hash'],['Acceptance','No authorized signature','Signed acceptance after evidence review']],[34,75,75]);
 table(wb,'Human Actions','Test and Verification Human Actions','These actions remain outside automated closure',['Action ID','Key','Action','Owner','Status','Closure evidence'],humanRows(),[18,22,80,34,36,65]);
 await save(wb,'07_Master_Test_and_Verification_Package.xlsx');
}

async function uat(){
 const wb=fresh(), hist=historicalRows();
 table(wb,'Control Summary','UAT, Field Test, and Usability Package - Canonical',payload.claim_boundary,['Metric','Value','Control'],[['Final participants',0,'Pending Researcher Evidence'],['Historical records',7,'Not final baseline'],['SUS items',10,'Controlled wording'],['SUS input','D5:D14','Includes row 5; whole 1-5'],['Acceptance','Pending','Authorized signature required']],[38,24,75]);
 table(wb,'Protocol','Final UAT Protocol','Protocol is prepared; execution remains human-owned',['Step','Owner','Required evidence','Status'],[['Consent and coded enrollment','Researcher','Consent/ethics record and participant code','Pending Researcher Evidence'],['Physical-device tasks','Owner / Researcher','Versioned logs/screenshots/observations','Not Executed'],['SUS administration','Researcher','Ten responses per participant','Pending Researcher Evidence'],['Acceptance review','Authorized representatives','Signed evidence review','Pending Authorized Signature']],[42,34,75,40]);
 table(wb,'Scenarios Tasks','UAT Scenarios and Tasks','No scenario result is pre-populated',['Scenario','Task','Required evidence','Status'],payload.human_gaps.map(x=>[x.action_id,x.action,x.closure_evidence,x.status]),[20,85,70,40]);
 table(wb,'Participant Form','Participant Form','Use coded identifiers only; no participant facts are invented',['Participant code','Consent reference','Session date','Researcher','Completion status'],[['','','','','Pending Researcher Evidence']],[24,34,24,34,40]);
 table(wb,'Farmer Profile','Farmer Profile Form','Collect only approved coded profile fields',['Participant code','Role/activity','Experience band','Device familiarity','Notes'],[['','','','','']],[24,38,28,34,60]);
 table(wb,'Device Build Matrix','Final Device / Build Matrix','Final 1.3.11+28 device execution remains pending',['Action ID','Activity','Owner','Status','Closure evidence'],payload.human_gaps.filter(x=>['android_device','iphone_device','tablet_device'].includes(x.action_key)).map(x=>[x.action_id,x.action,x.owner,x.status,x.closure_evidence]),[20,85,34,40,70]);
 table(wb,'Observations Results','Final UAT Observations / Results','No participant, device, performance, usability, or acceptance result is asserted',['Case ID','Activity','Status','Required evidence'],[['UAT-FINAL-001','Participant-coded final UAT','Pending Researcher Evidence','Consent, protocol execution, coded observations'],['DEVICE-FINAL-001','Physical Android/iPhone/tablet matrix','Not Executed - Human Action Required','Device/build IDs, timestamps, logs/screenshots/hashes'],['PERF-FINAL-001','Performance thresholds and measurements','Not Executed - Owner Action Required','Thresholds plus raw device measurements'],['ACCEPT-FINAL-001','Authorized acceptance','Pending Authorized Signature','Signed acceptance record']],[22,60,42,80]);
 table(wb,'Issues Retest','Historical Issues and Retest','Historical corrections do not close final human evidence',['Defect ID','Version','Description','Fix','Retest','Evidence path','SHA-256','Status'],payload.defects.map(r=>[r.defect_id,r.version,r.description,r.fix,r.retest,r.evidence_path,r.sha256,r.status]),[18,18,55,50,60,52,68,48]);
 table(wb,'Historical Evidence','Historical UAT Evidence - Exact Metadata','Date and round/revision are separate; unstated version remains unstated',['Evidence ID','Date','Round / revision','Version','Device','Runner / harness','Build workaround','Assessment bypass','Blocker','Observation','Evidence path','SHA-256','Layer'],hist,[18,18,18,18,52,52,52,44,55,65,52,68,38]);
 table(wb,'Version Comparison','Historical Version Comparison','Historical layers are not final 1.3.11+28 evidence',['Evidence ID','Date','Round / revision','Historical version','Final baseline','Layer'],payload.historical_uat.map(r=>[r.evidence_id,r.date,r.round_revision,r.version,payload.baseline.version,r.evidence_layer]),[18,18,18,22,22,38]);
 const s=wb.worksheets.add('SUS Response Form'); s.showGridLines=false; s.getRange('A1:D1').merge(); s.getRange('A1').values=[['System Usability Scale (SUS) - Controlled Instrument']]; s.getRange('A2:D2').merge(); s.getRange('A2').values=[[payload.sus.instrument+' | 1 = Strongly disagree | 5 = Strongly agree']]; s.getRange('A4:D4').values=[['Item','Approved item wording','Scale anchors','Response']]; s.getRange('A5:D14').values=payload.sus.items.map(x=>[`Item ${x.item}`,x.wording,'1 Strongly disagree / 5 Strongly agree','']); s.getRange('C16').values=[['SUS score']]; s.getRange('D16').formulas=[['=IF(COUNT(D5:D14)=10,(SUM(D5,D7,D9,D11,D13)-5+25-SUM(D6,D8,D10,D12,D14))*2.5,"")']]; s.getRange('A18:D18').merge(); s.getRange('A18').values=[['Formula contract: (odd items - 1 + 5 - even items) * 2.5; blank until all 10 responses exist']]; s.getRange('D5:D14').dataValidation={rule:{type:'whole',operator:'between',formula1:1,formula2:5}}; s.getRange('A1:D18').format={font,wrapText:true,verticalAlignment:'top'}; s.getRange('A1:D1').format={fill:'#17365D',font:{name:'Arial',size:16,bold:true,color:'#FFFFFF'},rowHeight:28}; s.getRange('A2:D2').format={fill:'#D9EAF7',font:{name:'Arial',size:9,italic:true,color:'#17365D'},rowHeight:30}; s.getRange('A4:D4').format={fill:'#2F75B5',font:{name:'Arial',size:9,bold:true,color:'#FFFFFF'},rowHeight:30}; ['A','B','C','D'].forEach((c,i)=>s.getRange(`${c}:${c}`).format.columnWidth=[14,85,38,16][i]); s.freezePanes.freezeRows(4);
 table(wb,'Evidence Index','UAT Evidence Index','Historical evidence is labeled; final human evidence remains pending',['Evidence ID','Date','Round / revision','Version','Path','SHA-256','Layer'],payload.historical_uat.map(r=>[r.evidence_id,r.date,r.round_revision,r.version,r.evidence_path,r.sha256,r.evidence_layer]),[18,18,18,18,55,68,40]);
 table(wb,'Acceptance Signoff','Acceptance Signoff','Authorized representatives sign only after evidence review',['Role','Name / identifier','Decision','Date','Signature / reference'],[['Owner / authorized approver','','Pending','',''],['Researcher','','Pending','','']],[38,34,24,24,55]);
 table(wb,'Limitations Human Actions','UAT Limitations and Human Actions','No automation substitutes for these actions',['Action ID','Key','Action','Owner','Status','Closure evidence'],humanRows(),[18,22,80,34,36,65]);
 await save(wb,'08_UAT_Field_Test_and_Usability_Package.xlsx');
}

await fs.mkdir(A,{recursive:true}); await audit(); await master(); await uat();
console.log(JSON.stringify({status:'canonical_workbooks_built',workbooks:3,sheets:41,tests:payload.tests.length,algorithm:payload.tests.filter(x=>x.category==='Algorithm / reference').length,boundary:payload.tests.filter(x=>x.category==='Invalid / boundary').length}));
