import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const ROOT=process.env.FSOOKTA_HANDOVER_ROOT || '/private/tmp/fsookta-final-handover';
const OUT=path.join(ROOT,'artifacts','10_Knowledge_Transfer_Deck.pptx');
const RENDER=path.join(ROOT,'renders','task7','deck');
const P=Presentation.create({slideSize:{width:1280,height:720}});
const C={ink:'#000000',panel:'#EDEDED',rule:'#B8BCC4',accent:'#6DCBF4',blue:'#3D8DFF',white:'#FFFFFF',muted:'#4B5563'};
const sources={
  repo:'Authoritative source commit bf8867a2083357cb9d60915bf6c2233801f923d8; pubspec.yaml',
  arch:'03_Final_Technical_Development_Report; 03 diagrams; lib/app; lib/screens; lib/core/services',
  data:'05_Local_Storage_and_Data_Management_Manual; 05_Data_Dictionary_and_Export_Schema; lib/app/app_state.dart',
  ai:'04_AI_Algorithm_and_Model_Technical_Report; 04_Algorithm_Recommendation_and_Reference_Matrices',
  test:'Task 2 raw logs; 07_Master_Test_and_Verification_Package; 08_UAT_Field_Test_and_Usability_Package',
  sec:'09_Security_Privacy_and_Data_Protection_Report; task7_offline_security_inspection.json',
};
function box(slide,name,x,y,w,h,fill=C.panel,line=C.rule){return slide.shapes.add({geometry:'rect',name,position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:line,width:1}})}
function text(slide,name,value,x,y,w,h,size=20,bold=false,color=C.ink,align='left'){
 const s=slide.shapes.add({geometry:'textbox',name,position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});s.text=value;s.text.style={fontSize:size,typeface:'Helvetica Neue',bold,color,alignment:align,verticalAlignment:'top',autoFit:'shrinkText'};return s;
}
function title(slide,value,n){text(slide,'slide-title',value,42,32,1130,84,38,true);text(slide,'slide-no',String(n).padStart(2,'0'),1184,660,54,22,16,false,C.ink,'right');}
function notes(slide,items){slide.speakerNotes.textFrame.setText(`[Sources]\n${items.join('\n')}\n[/Sources]\nPresenter note: Do not promote pending human actions to completed facts.`);slide.speakerNotes.setVisible(false);}
function cover(){const s=P.slides.add();s.background.fill=C.white;box(s,'codex-grid-layout-library#slide-08-media',660,42,580,588,'#EAF5FB');
 text(s,'cover-title','SookTa\nKnowledge Transfer',42,54,570,160,56,true);text(s,'cover-body','Final handover baseline\n1.3.11+28\n\nA source-grounded guide to architecture, data, algorithms, release boundaries and ownership actions.',42,244,540,310,26,false);text(s,'cover-accent','TECHNICAL HANDOVER',714,102,440,42,24,true,C.blue);text(s,'cover-right','Full-history repository is authoritative\n\nLocal-first assessment\nDeterministic reference rules\nBundled model assistance\nOptional telemetry, default-off',714,190,440,280,24,false);text(s,'slide-no','01',1184,660,54,22,16,false,C.ink,'right');notes(s,[sources.repo,sources.arch]);}
function metrics(n,t,intro,stats,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);text(s,'intro',intro,42,118,1160,120,21,false);stats.forEach((a,i)=>{const x=42+i*411;box(s,`codex-grid-layout-library#slide-19-panel-${i+1}`,x,318,374,310);text(s,`stat-${i+1}`,a[0],x+32,354,310,116,48,true,C.blue);text(s,`stat-body-${i+1}`,a[1],x+32,505,310,92,22,false)});notes(s,src);}
function timeline(n,t,steps,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);box(s,'codex-grid-layout-library#slide-17-rule',36,354,1200,2,C.ink,C.ink);steps.forEach((a,i)=>{const x=42+i*400;box(s,`node-${i+1}`,x,346,14,14,C.ink,C.ink);text(s,`label-${i+1}`,a[0],x,290,300,42,24,true);text(s,`body-${i+1}`,a[1],x,400,330,180,24,false)});notes(s,src);}
function evidence(n,t,intro,rows,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);text(s,'intro',intro,42,112,1160,90,20,false);const y0=228;rows.forEach((r,i)=>{const y=y0+i*62;box(s,`codex-grid-layout-library#slide-14-row-${i+1}`,42,y,1196,56,i===0?'#D0EDFA':(i%2?'#FFFFFF':'#F5F5F5'));text(s,`c1-${i}`,r[0],58,y+10,260,36,i===0?18:16,i===0);text(s,`c2-${i}`,r[1],330,y+10,450,36,i===0?18:16,i===0);text(s,`c3-${i}`,r[2],795,y+10,425,36,i===0?18:16,i===0)});notes(s,src);}
function split(n,t,leftTitle,leftBody,rightTitle,rightBody,src){const s=P.slides.add();s.background.fill=C.white;title(s,t,n);text(s,'left-title',leftTitle,42,194,530,48,26,true);text(s,'left-body',leftBody,42,254,540,340,22,false);box(s,'codex-grid-layout-library#slide-08-media',658,164,580,466,'#EAF5FB');text(s,'right-title',rightTitle,700,214,490,52,26,true,C.blue);text(s,'right-body',rightBody,700,286,490,260,22,false);notes(s,src);}

cover();
metrics(2,'The handover is technically reproducible — acceptance is still human-owned','The baseline is frozen and evidence-backed. Counts describe technical package evidence, not field validation or formal acceptance.',[['1.3.11+28','Final application version'],['135','Reproduced automated tests'],['0','Final participant/SUS results']], [sources.repo,sources.test]);
split(3,'The app is a local-first Flutter assessment client','Core architecture','Screens and app state coordinate coded profiles, four-image/video assessment, REBA/ISO calculation, recommendations, history and CSV export.','Network boundary','Core assessment does not require a remote assessment database or API. Firebase telemetry is optional and default-off.',[sources.arch,sources.sec]);
timeline(4,'One controlled workflow connects collection to evidence',[['COLLECT','Coded profile\nActivity + method\nFour images / video'],['ASSESS','Eligibility + pose\nREBA / ISO rules\nAdvisory models'],['RETAIN / SHARE','Local history\nCSV export\nResearcher policy boundary']],[sources.arch,sources.data,sources.ai]);
evidence(5,'Repository history is the delivery authority','The clean snapshot is supplementary; ownership transfer must preserve history and access controls.',[['Asset','Authority','Human gate'],['Full-history repository','Authoritative','GitHub Owner/Admin transfer'],['Clean source archive','Supplementary snapshot','Verify tree/hash'],['Store/config/signing','External systems','Secure owner transfer'],['Generated handover package','Reference evidence','Drive audit and readback']],[sources.repo]);
timeline(6,'Local persistence ends at the share boundary',[['STORE','SharedPreferences JSON\nApp-documents media'],['EXPORT','CSV written locally\nOS share sheet'],['GOVERN','Approved destination\nRetention / deletion\nIncident response']],[sources.data,sources.sec]);
metrics(7,'Algorithms are traceable, but validation claims stay bounded','Deterministic REBA/ISO rules and model roles are documented with paths/hashes. Missing governed data and metrics remain explicit.',[['55','Algorithm/reference cases'],['10','Model / algorithm roles'],['2','XGBoost gaps: dataset + raw metrics']],[sources.ai,sources.test]);
evidence(8,'Privacy controls are partly technical and partly procedural','The offline source-backed inspection is disclosed; it is not a sealed security report or compliance certification.',[['Boundary','Current evidence','Required closure'],['Telemetry','Default-off build define','Owner/research approval + console policy'],['Local records/media','Sandboxed app paths','Retention, backup and deletion procedure'],['CSV share','User-triggered OS share','Approved destination + recipient controls'],['Credentials/signing','Categories only; no values','Secure transfer, rotation and revocation'],['Incidents','Draft actions','Approved contacts, SLA and exercise']],[sources.sec]);
metrics(9,'Automated evidence is strong; release and field gates remain open','Host/unit/widget results support technical confidence. They do not replace physical-device, participant, SUS, performance or acceptance evidence.',[['135','Automated tests passed'],['7','Historical UAT records'],['0','Final UAT / SUS / acceptance']],[sources.test]);
timeline(10,'Production release requires three owner-controlled gates',[['SIGN','Android upload key\nApple distribution assets'],['VALIDATE','Physical devices\nPerformance + UAT\nResearch review'],['PUBLISH','Store roles\nRelease approval\nVersion/tag evidence']],[sources.repo,sources.test]);
split(11,'Operations depend on explicit custody and recovery rules','Current behavior','Records, drafts and media are local. Exports can leave the app through the OS share sheet. No governed automated backup/restore is evidenced.','Required operating procedure','Approve device custody, backup/restore test, retention/deletion schedule, secure transfer destination and incident contacts before field use.',[sources.data,sources.sec]);
evidence(12,'Troubleshooting starts with bounded evidence','Escalate with coded identifiers, version, device, timestamp, exact steps and non-identifying logs.',[['Symptom','First response','Do not do'],['Camera/gallery denied','Check OS permission and retry','Do not grant unrelated access'],['Pose/person-count failure','One visible person; improve frame/light','Do not treat failure as low risk'],['Export/share failure','Check storage/destination app','Do not use unapproved channels'],['Missing local data','Stop, preserve facts, notify owner','Do not reconstruct participant facts'],['Build/signing failure','Check toolchain and owner assets','Do not label technical build production']],[sources.data,sources.test,sources.sec]);
timeline(13,'Ownership transfer is a controlled evidence sequence',[['TRANSFER','GitHub / Firebase\nApple / Google Play\nSigning categories'],['VERIFY','Named roles\nReadback / audit trail\nRotation decision'],['ACKNOWLEDGE','KT minutes\nOpen actions\nAuthorized signatures']],[sources.repo,sources.sec]);
metrics(14,'Close the handover with evidence, not assumptions','Review each open action, attach authoritative closure evidence, then obtain authorized decisions and signatures. Until then, the package is technically prepared — not finally accepted.',[['5','Owner / researcher action groups'],['3','KT acknowledgement roles'],['1','Next step: evidence review meeting']],[sources.sec,sources.test,'10_Knowledge_Transfer_Minutes.docx; 12 sign-off controls']);

await fs.mkdir(path.dirname(OUT),{recursive:true});await fs.mkdir(RENDER,{recursive:true});
for(const [i,s] of P.slides.items.entries()){
 const stem=`slide-${String(i+1).padStart(2,'0')}`;
 const png=await P.export({slide:s,format:'png',scale:2});await fs.writeFile(path.join(RENDER,`${stem}.png`),new Uint8Array(await png.arrayBuffer()));
 const layout=await s.export({format:'layout'});await fs.writeFile(path.join(RENDER,`${stem}.layout.json`),await layout.text());
}
const montage=await P.export({format:'webp',montage:true,scale:1});await fs.writeFile(path.join(RENDER,'deck-montage.webp'),new Uint8Array(await montage.arrayBuffer()));
const inspection=await P.inspect({kind:'slide,textbox,shape,notes',maxChars:40000});await fs.writeFile(path.join(RENDER,'deck-inspection.ndjson'),inspection.ndjson);
const pptx=await PresentationFile.exportPptx(P);await pptx.save(OUT);
console.log(JSON.stringify({status:'built',slides:P.slides.items.length,render_dir:RENDER,output:OUT}));
