#!/usr/bin/env python3
"""Consume, but never author, an external manual Task 6 visual decision."""
import argparse
import hashlib
import json
from pathlib import Path


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def consume(expected_path: Path, decision_path: Path, output_path: Path) -> dict:
    expected = json.loads(expected_path.read_text())
    decision = json.loads(decision_path.read_text())
    if decision.get('decision') != 'PASS' or not decision.get('inspector') or not decision.get('inspected_at'):
        raise ValueError('external manual PASS decision with inspector and timestamp required')
    if decision.get('expected_manifest_sha256') != sha(expected_path):
        raise ValueError('manual decision is not bound to the expected render manifest')
    if decision.get('expected_render_count') != expected.get('count'):
        raise ValueError('manual decision render count mismatch')
    record = {
        'schema_version': 2,
        'source': 'external manual decision; not generated by builder or recorder',
        'decision': decision['decision'],
        'inspector': decision['inspector'],
        'inspected_at': decision['inspected_at'],
        'expected_manifest_sha256': sha(expected_path),
        'expected_render_count': expected['count'],
        'external_decision_path': str(decision_path),
        'external_decision_sha256': sha(decision_path),
        'scope': decision.get('scope', ''),
    }
    output_path.write_text(json.dumps(record, indent=2) + '\n')
    return record


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--expected', type=Path, required=True)
    parser.add_argument('--decision', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(consume(args.expected, args.decision, args.output), indent=2))
